// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * CommandGroup 命令组定义
 */
export class CommandGroup {
    /**
     * 唯一标识（UUID）
     */
    "id": string;

    /**
     * 命令组名称
     */
    "name": string;

    /**
     * 描述信息
     */
    "description": string;

    /**
     * 命令列表
     */
    "commands": string[];

    /**
     * 创建时间
     */
    "createdAt": string;

    /**
     * 更新时间
     */
    "updatedAt": string;

    /**
     * 标签（用于分类）
     */
    "tags": string[];

    /** Creates a new CommandGroup instance. */
    constructor($$source: Partial<CommandGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandGroup {
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new CommandGroup($$parsedSource as Partial<CommandGroup>);
    }
}

/**
 * DeviceAsset 表示单台交换机的连接凭证信息
 */
export class DeviceAsset {
    "id": number;
    "ip": string;
    "port": number;

    /**
     * 连接协议：SSH/SNMP/TELNET
     */
    "protocol": string;
    "username": string;
    "password": string;

    /**
     * 设备分组
     */
    "group": string;

    /**
     * 设备标签列表
     */
    "tags": string[];

    /** Creates a new DeviceAsset instance. */
    constructor($$source: Partial<DeviceAsset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceAsset {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new DeviceAsset($$parsedSource as Partial<DeviceAsset>);
    }
}

/**
 * GlobalSettings 全局运行参数
 */
export class GlobalSettings {
    "id": number;

    /**
     * 并发数 (当前硬编码为 32)
     */
    "maxWorkers": number;

    /**
     * SSH/SFTP 连接超时 (如 "10s")
     */
    "connectTimeout": string;

    /**
     * 单条命令默认超时 (如 "30s")
     */
    "commandTimeout": string;

    /**
     * 回显输出与配置备份的根目录
     */
    "outputDir": string;

    /**
     * 系统运行日志存放目录
     */
    "logDir": string;

    /**
     * "pause" | "skip" | "abort"
     */
    "errorMode": string;

    /**
     * 调试日志开关
     * 启用 DEBUG 级别日志
     */
    "debug": boolean;

    /**
     * 启用全量 DEBUG 级别日志（包含 Debug）
     */
    "debugAll": boolean;

    /**
     * SSH算法配置
     */
    "sshAlgorithms": SSHAlgorithmSettings;

    /** Creates a new GlobalSettings instance. */
    constructor($$source: Partial<GlobalSettings> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("connectTimeout" in $$source)) {
            this["connectTimeout"] = "";
        }
        if (!("commandTimeout" in $$source)) {
            this["commandTimeout"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("logDir" in $$source)) {
            this["logDir"] = "";
        }
        if (!("errorMode" in $$source)) {
            this["errorMode"] = "";
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("debugAll" in $$source)) {
            this["debugAll"] = false;
        }
        if (!("sshAlgorithms" in $$source)) {
            this["sshAlgorithms"] = (new SSHAlgorithmSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalSettings {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sshAlgorithms" in $$parsedSource) {
            $$parsedSource["sshAlgorithms"] = $$createField9_0($$parsedSource["sshAlgorithms"]);
        }
        return new GlobalSettings($$parsedSource as Partial<GlobalSettings>);
    }
}

/**
 * SSHAlgorithmSettings SSH算法配置
 */
export class SSHAlgorithmSettings {
    /**
     * 加密算法 (Ciphers)
     */
    "ciphers": string[];

    /**
     * 密钥交换算法
     */
    "keyExchanges": string[];

    /**
     * 消息认证码
     */
    "macs": string[];

    /**
     * 主机密钥算法
     */
    "hostKeyAlgorithms": string[];

    /**
     * 预设模式: "secure" | "compatible" | "custom"
     */
    "presetMode": string;

    /** Creates a new SSHAlgorithmSettings instance. */
    constructor($$source: Partial<SSHAlgorithmSettings> = {}) {
        if (!("ciphers" in $$source)) {
            this["ciphers"] = [];
        }
        if (!("keyExchanges" in $$source)) {
            this["keyExchanges"] = [];
        }
        if (!("macs" in $$source)) {
            this["macs"] = [];
        }
        if (!("hostKeyAlgorithms" in $$source)) {
            this["hostKeyAlgorithms"] = [];
        }
        if (!("presetMode" in $$source)) {
            this["presetMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAlgorithmSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAlgorithmSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField0_0($$parsedSource["ciphers"]);
        }
        if ("keyExchanges" in $$parsedSource) {
            $$parsedSource["keyExchanges"] = $$createField1_0($$parsedSource["keyExchanges"]);
        }
        if ("macs" in $$parsedSource) {
            $$parsedSource["macs"] = $$createField2_0($$parsedSource["macs"]);
        }
        if ("hostKeyAlgorithms" in $$parsedSource) {
            $$parsedSource["hostKeyAlgorithms"] = $$createField3_0($$parsedSource["hostKeyAlgorithms"]);
        }
        return new SSHAlgorithmSettings($$parsedSource as Partial<SSHAlgorithmSettings>);
    }
}

/**
 * TaskGroup 任务组
 */
export class TaskGroup {
    "id": string;
    "name": string;
    "description": string;

    /**
     * "group" 模式A | "binding" 模式B
     */
    "mode": string;

    /**
     * 任务项列表
     */
    "items": TaskItem[];

    /**
     * 标签
     */
    "tags": string[];

    /**
     * "pending" | "running" | "completed" | "failed"
     */
    "status": string;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new TaskGroup instance. */
    constructor($$source: Partial<TaskGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskGroup {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new TaskGroup($$parsedSource as Partial<TaskGroup>);
    }
}

/**
 * TaskItem 单个任务项（一组命令绑定一组设备）
 */
export class TaskItem {
    /**
     * 命令组ID（模式A使用）
     */
    "commandGroupId": string;

    /**
     * 直接命令列表（模式B使用）
     */
    "commands": string[];

    /**
     * 绑定的设备IP列表
     */
    "deviceIPs": string[];

    /** Creates a new TaskItem instance. */
    constructor($$source: Partial<TaskItem> = {}) {
        if (!("commandGroupId" in $$source)) {
            this["commandGroupId"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("deviceIPs" in $$source)) {
            this["deviceIPs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskItem {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField1_0($$parsedSource["commands"]);
        }
        if ("deviceIPs" in $$parsedSource) {
            $$parsedSource["deviceIPs"] = $$createField2_0($$parsedSource["deviceIPs"]);
        }
        return new TaskItem($$parsedSource as Partial<TaskItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SSHAlgorithmSettings.createFrom;
const $$createType2 = TaskItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
