// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 包装所有要暴露给 Wails Frontend 的绑定方法
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as executor$0 from "../executor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * EnsureConfig 检查必需配置文件并返回是否有文件遗漏，以便前端提示
 * @returns {Promise<[config$0.DeviceAsset[], string[], string[]]> & { cancel(): void }}
 */
export function EnsureConfig() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(2944363242));
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      $result[0] = $$createType1($result[0]);
      $result[1] = $$createType2($result[1]);
      $result[2] = $$createType2($result[2]);
      return $result;
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * LoadSettings 获取合并后的主配置
 * @returns {Promise<config$0.GlobalSettings | null> & { cancel(): void }}
 */
export function LoadSettings() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(3584902543));
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      return $$createType4($result);
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 * @param {string} ip
 * @param {string} action
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ResolveSuspend(ip, action) {
  let $resultPromise = /** @type {any} */ ($Call.ByID(3815659806, ip, action));
  return $resultPromise;
}

/**
 * ServiceStartup Wails 应用启动时的生命周期狗子
 * @param {application$0.ServiceOptions} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ServiceStartup(options) {
  let $resultPromise = /** @type {any} */ ($Call.ByID(2632958766, options));
  return $resultPromise;
}

/**
 * StartEngineWails 启动核心下发动作（UI包裹层）
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartEngineWails() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(1094601454));
  return $resultPromise;
}

/**
 * StartBackupWails 启动核心备份动作（UI包裹层）
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartBackupWails() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.StartBackupWails",
    )
  );
  return $resultPromise;
}

/**
 * WailsSuspendHandler 构建代理 Suspend 钩子替换原先的控制台询问方式
 * @returns {Promise<executor$0.SuspendHandler> & { cancel(): void }}
 */
export function WailsSuspendHandler() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(269849284));
  return $resultPromise;
}

/**
 * GetCommands 获取命令列表
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function GetCommands() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.GetCommands",
    )
  );
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      return $$createType2($result);
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * SaveCommands 保存命令列表
 * @param {string[]} commands
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveCommands(commands) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.SaveCommands",
      commands,
    )
  );
  return $resultPromise;
}

// Private type creation functions
const $$createType0 = config$0.DeviceAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = config$0.GlobalSettings.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
