// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 包装所有要暴露给 Wails Frontend 的绑定方法
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as executor$0 from "../executor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * EnsureConfig 检查必需配置文件并返回是否有文件遗漏，以便前端提示
 * @returns {Promise<[config$0.DeviceAsset[], string[], string[]]> & { cancel(): void }}
 */
export function EnsureConfig() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(2944363242));
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      $result[0] = $$createType1($result[0]);
      $result[1] = $$createType2($result[1]);
      $result[2] = $$createType2($result[2]);
      return $result;
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * LoadSettings 获取合并后的主配置
 * @returns {Promise<config$0.GlobalSettings | null> & { cancel(): void }}
 */
export function LoadSettings() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(3584902543));
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      return $$createType4($result);
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 * @param {string} ip
 * @param {string} action
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ResolveSuspend(ip, action) {
  let $resultPromise = /** @type {any} */ ($Call.ByID(3815659806, ip, action));
  return $resultPromise;
}

/**
 * ServiceStartup Wails 应用启动时的生命周期狗子
 * @param {application$0.ServiceOptions} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ServiceStartup(options) {
  let $resultPromise = /** @type {any} */ ($Call.ByID(2632958766, options));
  return $resultPromise;
}

/**
 * StartEngineWails 启动核心下发动作（UI包裹层）
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartEngineWails() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(1094601454));
  return $resultPromise;
}

/**
 * StartBackupWails 启动核心备份动作（UI包裹层）
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartBackupWails() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.StartBackupWails",
    )
  );
  return $resultPromise;
}

/**
 * WailsSuspendHandler 构建代理 Suspend 钩子替换原先的控制台询问方式
 * @returns {Promise<executor$0.SuspendHandler> & { cancel(): void }}
 */
export function WailsSuspendHandler() {
  let $resultPromise = /** @type {any} */ ($Call.ByID(269849284));
  return $resultPromise;
}

/**
 * GetCommands 获取命令列表
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function GetCommands() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.GetCommands",
    )
  );
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      return $$createType2($result);
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * SaveCommands 保存命令列表
 * @param {string[]} commands
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveCommands(commands) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.SaveCommands",
      commands,
    )
  );
  return $resultPromise;
}

/**
 * ListCommandGroups 获取所有命令组列表
 * @returns {Promise<any[]> & { cancel(): void }}
 */
export function ListCommandGroups() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.ListCommandGroups",
    )
  );
  return $resultPromise;
}

/**
 * GetCommandGroup 根据 ID 获取单个命令组
 * @param {string} id
 * @returns {Promise<any> & { cancel(): void }}
 */
export function GetCommandGroup(id) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.GetCommandGroup",
      id,
    )
  );
  return $resultPromise;
}

/**
 * CreateCommandGroup 创建新命令组
 * @param {object} group
 * @returns {Promise<any> & { cancel(): void }}
 */
export function CreateCommandGroup(group) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.CreateCommandGroup",
      group,
    )
  );
  return $resultPromise;
}

/**
 * UpdateCommandGroup 更新命令组
 * @param {string} id
 * @param {object} group
 * @returns {Promise<any> & { cancel(): void }}
 */
export function UpdateCommandGroup(id, group) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.UpdateCommandGroup",
      id,
      group,
    )
  );
  return $resultPromise;
}

/**
 * DeleteCommandGroup 删除命令组
 * @param {string} id
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteCommandGroup(id) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.DeleteCommandGroup",
      id,
    )
  );
  return $resultPromise;
}

/**
 * DuplicateCommandGroup 复制命令组
 * @param {string} id
 * @returns {Promise<any> & { cancel(): void }}
 */
export function DuplicateCommandGroup(id) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.DuplicateCommandGroup",
      id,
    )
  );
  return $resultPromise;
}

/**
 * ImportCommandGroup 从文件导入命令组
 * @param {string} filePath
 * @returns {Promise<any> & { cancel(): void }}
 */
export function ImportCommandGroup(filePath) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.ImportCommandGroup",
      filePath,
    )
  );
  return $resultPromise;
}

/**
 * ExportCommandGroup 导出命令组到文件
 * @param {string} id
 * @param {string} filePath
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ExportCommandGroup(id, filePath) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.ExportCommandGroup",
      id,
      filePath,
    )
  );
  return $resultPromise;
}

/**
 * StartEngineWithSelection 使用选定的设备和命令组启动引擎
 * @param {string[]} deviceIPs
 * @param {string} commandGroupID
 * @returns {Promise<void> & { cancel(): void }}
 */
export function StartEngineWithSelection(deviceIPs, commandGroupID) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.StartEngineWithSelection",
      deviceIPs,
      commandGroupID,
    )
  );
  return $resultPromise;
}

/**
 * ListDevices 获取设备列表
 * @returns {Promise<config$0.DeviceAsset[]> & { cancel(): void }}
 */
export function ListDevices() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.ListDevices",
    )
  );
  let $typingPromise = /** @type {any} */ (
    $resultPromise.then((/** @type {any} */ $result) => {
      return $$createType1($result);
    })
  );
  $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
  return $typingPromise;
}

/**
 * AddDevice 新增设备
 * @param {config$0.DeviceAsset} device
 * @returns {Promise<void> & { cancel(): void }}
 */
export function AddDevice(device) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.AddDevice",
      device,
    )
  );
  return $resultPromise;
}

/**
 * UpdateDevice 更新设备
 * @param {number} index
 * @param {config$0.DeviceAsset} device
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateDevice(index, device) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.UpdateDevice",
      index,
      device,
    )
  );
  return $resultPromise;
}

/**
 * DeleteDevice 删除设备
 * @param {number} index
 * @returns {Promise<void> & { cancel(): void }}
 */
export function DeleteDevice(index) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.DeleteDevice",
      index,
    )
  );
  return $resultPromise;
}

/**
 * SaveDevices 批量保存设备列表
 * @param {config$0.DeviceAsset[]} devices
 * @returns {Promise<void> & { cancel(): void }}
 */
export function SaveDevices(devices) {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.SaveDevices",
      devices,
    )
  );
  return $resultPromise;
}

/**
 * GetProtocolDefaultPorts 获取协议默认端口映射
 * @returns {Promise<Record<string, number>> & { cancel(): void }}
 */
export function GetProtocolDefaultPorts() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.GetProtocolDefaultPorts",
    )
  );
  return $resultPromise;
}

/**
 * GetValidProtocols 获取有效协议列表
 * @returns {Promise<string[]> & { cancel(): void }}
 */
export function GetValidProtocols() {
  let $resultPromise = /** @type {any} */ (
    $Call.ByName(
      "github.com/NetWeaverGo/core/internal/ui.AppService.GetValidProtocols",
    )
  );
  return $resultPromise;
}

// Private type creation functions
const $$createType0 = config$0.DeviceAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = config$0.GlobalSettings.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
