// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandGroupService 命令组管理服务 - 负责命令组的增删改查和导入导出
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * CreateCommandGroup 创建新命令组
 */
export function CreateCommandGroup(group: config$0.CommandGroup): $CancellablePromise<config$0.CommandGroup | null> {
    return $Call.ByID(3085661725, group).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteCommandGroup 删除命令组
 */
export function DeleteCommandGroup(id: string): $CancellablePromise<void> {
    return $Call.ByID(53539042, id);
}

/**
 * DuplicateCommandGroup 复制命令组
 */
export function DuplicateCommandGroup(id: string): $CancellablePromise<config$0.CommandGroup | null> {
    return $Call.ByID(1880070542, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportCommandGroup 导出命令组到文件
 */
export function ExportCommandGroup(id: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2675289651, id, filePath);
}

/**
 * GetCommandGroup 根据 ID 获取单个命令组
 */
export function GetCommandGroup(id: string): $CancellablePromise<config$0.CommandGroup | null> {
    return $Call.ByID(566479847, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCommands 获取命令列表（兼容旧接口）
 */
export function GetCommands(): $CancellablePromise<string[]> {
    return $Call.ByID(1222284357).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ImportCommandGroup 从文件导入命令组
 */
export function ImportCommandGroup(filePath: string): $CancellablePromise<config$0.CommandGroup | null> {
    return $Call.ByID(1574742228, filePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListCommandGroups 获取所有命令组列表
 */
export function ListCommandGroups(): $CancellablePromise<config$0.CommandGroup[]> {
    return $Call.ByID(1228011110).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveCommands 保存命令列表（兼容旧接口）
 */
export function SaveCommands(commands: string[]): $CancellablePromise<void> {
    return $Call.ByID(27404006, commands);
}

/**
 * UpdateCommandGroup 更新命令组
 */
export function UpdateCommandGroup(id: string, group: config$0.CommandGroup): $CancellablePromise<config$0.CommandGroup | null> {
    return $Call.ByID(4162611892, id, group).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.CommandGroup.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
