// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandGroupService 命令组管理服务 - 负责命令组的增删改查和导入导出
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * CreateCommandGroup 创建新命令组
 */
export function CreateCommandGroup(group: config$0.CommandGroup): Promise<config$0.CommandGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3085661725, group) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteCommandGroup 删除命令组
 */
export function DeleteCommandGroup(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(53539042, id) as any;
    return $resultPromise;
}

/**
 * DuplicateCommandGroup 复制命令组
 */
export function DuplicateCommandGroup(id: string): Promise<config$0.CommandGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1880070542, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ExportCommandGroup 导出命令组到文件
 */
export function ExportCommandGroup(id: string, filePath: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2675289651, id, filePath) as any;
    return $resultPromise;
}

/**
 * GetCommandGroup 根据 ID 获取单个命令组
 */
export function GetCommandGroup(id: string): Promise<config$0.CommandGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(566479847, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetCommands 获取命令列表（兼容旧接口）
 */
export function GetCommands(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1222284357) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ImportCommandGroup 从文件导入命令组
 */
export function ImportCommandGroup(filePath: string): Promise<config$0.CommandGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1574742228, filePath) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ListCommandGroups 获取所有命令组列表
 */
export function ListCommandGroups(): Promise<config$0.CommandGroup[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1228011110) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SaveCommands 保存命令列表（兼容旧接口）
 */
export function SaveCommands(commands: string[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(27404006, commands) as any;
    return $resultPromise;
}

/**
 * ServiceStartup Wails 服务启动生命周期钩子
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3886900581, options) as any;
    return $resultPromise;
}

/**
 * UpdateCommandGroup 更新命令组
 */
export function UpdateCommandGroup(id: string, group: config$0.CommandGroup): Promise<config$0.CommandGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4162611892, id, group) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = config$0.CommandGroup.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType0);
