// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 设备管理服务 - 负责设备的增删改查
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * AddDevice 新增设备
 */
export function AddDevice(device: config$0.DeviceAsset): $CancellablePromise<void> {
    return $Call.ByID(728011368, device);
}

/**
 * DeleteDevice 删除设备
 */
export function DeleteDevice(index: number): $CancellablePromise<void> {
    return $Call.ByID(2793883322, index);
}

/**
 * GetProtocolDefaultPorts 获取协议默认端口映射
 */
export function GetProtocolDefaultPorts(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(939599686).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetValidProtocols 获取有效协议列表
 */
export function GetValidProtocols(): $CancellablePromise<string[]> {
    return $Call.ByID(1194827734).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListDevices 获取设备列表
 */
export function ListDevices(): $CancellablePromise<config$0.DeviceAsset[]> {
    return $Call.ByID(779205990).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveDevices 批量保存设备列表
 */
export function SaveDevices(devices: config$0.DeviceAsset[]): $CancellablePromise<void> {
    return $Call.ByID(3296917977, devices);
}

/**
 * UpdateDevice 更新设备
 */
export function UpdateDevice(index: number, device: config$0.DeviceAsset): $CancellablePromise<void> {
    return $Call.ByID(350852692, index, device);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = config$0.DeviceAsset.createFrom;
const $$createType3 = $Create.Array($$createType2);
