// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 设备管理服务 - 负责设备的增删改查
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddDevice 新增设备
 */
export function AddDevice(device: config$0.DeviceAsset): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(728011368, device) as any;
    return $resultPromise;
}

/**
 * DeleteDevice 删除设备
 */
export function DeleteDevice(index: number): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2793883322, index) as any;
    return $resultPromise;
}

/**
 * GetProtocolDefaultPorts 获取协议默认端口映射
 */
export function GetProtocolDefaultPorts(): Promise<{ [_: string]: number }> & { cancel(): void } {
    let $resultPromise = $Call.ByID(939599686) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetValidProtocols 获取有效协议列表
 */
export function GetValidProtocols(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1194827734) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ListDevices 获取设备列表
 */
export function ListDevices(): Promise<config$0.DeviceAsset[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(779205990) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * SaveDevices 批量保存设备列表
 */
export function SaveDevices(devices: config$0.DeviceAsset[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3296917977, devices) as any;
    return $resultPromise;
}

/**
 * ServiceStartup Wails 服务启动生命周期钩子
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4240766859, options) as any;
    return $resultPromise;
}

/**
 * UpdateDevice 更新设备
 */
export function UpdateDevice(index: number, device: config$0.DeviceAsset): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(350852692, index, device) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = config$0.DeviceAsset.createFrom;
const $$createType3 = $Create.Array($$createType2);
