// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 设备管理服务 - 负责设备的增删改查
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * AddDevice 新增设备
 */
export function AddDevice(device: models$0.DeviceAsset): $CancellablePromise<void> {
    return $Call.ByID(728011368, device);
}

/**
 * AddDevices 批量新增设备
 */
export function AddDevices(devices: models$0.DeviceAsset[]): $CancellablePromise<void> {
    return $Call.ByID(1783758977, devices);
}

/**
 * DeleteDevice 删除设备
 */
export function DeleteDevice(id: number): $CancellablePromise<void> {
    return $Call.ByID(2793883322, id);
}

/**
 * DeleteDevices 批量删除设备
 */
export function DeleteDevices(ids: number[]): $CancellablePromise<void> {
    return $Call.ByID(4025773675, ids);
}

/**
 * GetDeviceByID 根据 ID 获取单个设备详情（包含解密后的密码，用于编辑）
 */
export function GetDeviceByID(id: number): $CancellablePromise<models$0.DeviceAssetResponse | null> {
    return $Call.ByID(2763577531, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProtocolDefaultPorts 获取协议默认端口映射
 */
export function GetProtocolDefaultPorts(): $CancellablePromise<{ [_ in string]?: number }> {
    return $Call.ByID(939599686).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetValidProtocols 获取有效协议列表
 */
export function GetValidProtocols(): $CancellablePromise<string[]> {
    return $Call.ByID(1194827734).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListDevices 获取设备列表
 */
export function ListDevices(): $CancellablePromise<models$0.DeviceAsset[]> {
    return $Call.ByID(779205990).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateDevice 更新设备
 */
export function UpdateDevice(id: number, device: models$0.DeviceAsset): $CancellablePromise<void> {
    return $Call.ByID(350852692, id, device);
}

/**
 * UpdateDevices 批量更新设备
 */
export function UpdateDevices(devices: models$0.DeviceAsset[]): $CancellablePromise<void> {
    return $Call.ByID(314007397, devices);
}

// Private type creation functions
const $$createType0 = models$0.DeviceAssetResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = models$0.DeviceAsset.createFrom;
const $$createType5 = $Create.Array($$createType4);
