// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService 发现任务服务 - 负责拓扑发现任务的管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as parser$0 from "../parser/models.js";

/**
 * BuildTopology 构建拓扑图
 */
export function BuildTopology(taskID: string): $CancellablePromise<models$0.TopologyBuildResult | null> {
    return $Call.ByID(1234689032, taskID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CancelDiscovery 取消发现任务
 */
export function CancelDiscovery(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2827233845, taskID);
}

/**
 * GetCurrentDiscoveryTask 获取当前运行的任务ID
 */
export function GetCurrentDiscoveryTask(): $CancellablePromise<string> {
    return $Call.ByID(2205226273);
}

/**
 * GetDeviceTopologyDetail 获取设备的拓扑详情
 */
export function GetDeviceTopologyDetail(taskID: string, deviceIP: string): $CancellablePromise<parser$0.ParsedResult | null> {
    return $Call.ByID(3208315579, taskID, deviceIP).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetEdgeDetail 获取边详情
 */
export function GetEdgeDetail(taskID: string, edgeID: string): $CancellablePromise<models$0.TopologyEdgeDetailView | null> {
    return $Call.ByID(1537747477, taskID, edgeID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetRawOutput 获取原始命令输出
 */
export function GetRawOutput(taskID: string, deviceIP: string, commandKey: string): $CancellablePromise<string> {
    return $Call.ByID(3454866016, taskID, deviceIP, commandKey);
}

/**
 * GetSupportedVendors 获取支持的厂商列表
 */
export function GetSupportedVendors(): $CancellablePromise<string[]> {
    return $Call.ByID(3311268684).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetTaskDevices 获取任务下的设备列表
 */
export function GetTaskDevices(taskID: string): $CancellablePromise<discovery$0.DiscoveryDeviceView[]> {
    return $Call.ByID(870059783, taskID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetTaskStatus 获取任务状态
 */
export function GetTaskStatus(taskID: string): $CancellablePromise<discovery$0.DiscoveryTaskView | null> {
    return $Call.ByID(1710880238, taskID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetTopologyGraph 获取拓扑图视图
 */
export function GetTopologyGraph(taskID: string): $CancellablePromise<models$0.TopologyGraphView | null> {
    return $Call.ByID(3976830640, taskID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetVendorProfiles 获取所有厂商命令配置
 */
export function GetVendorProfiles(): $CancellablePromise<(discovery$0.VendorCommandProfile | null)[]> {
    return $Call.ByID(2906719573).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * IsDiscoveryRunning 检查是否有发现任务在运行
 */
export function IsDiscoveryRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3301156278);
}

/**
 * ListDiscoveryTasks 列出所有发现任务
 */
export function ListDiscoveryTasks(limit: number): $CancellablePromise<discovery$0.DiscoveryTaskView[]> {
    return $Call.ByID(3407912979, limit).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ParseDiscoveryTask 解析发现任务的原始输出
 */
export function ParseDiscoveryTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2963448101, taskID);
}

/**
 * RetryFailedDevices 重试失败的设备
 */
export function RetryFailedDevices(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(610298369, taskID);
}

/**
 * StartDiscovery 启动发现任务
 */
export function StartDiscovery(req: discovery$0.StartDiscoveryRequest): $CancellablePromise<discovery$0.TaskStartResponse> {
    return $Call.ByID(2474301625, req).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.TopologyBuildResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = parser$0.ParsedResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.TopologyEdgeDetailView.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = models$0.DiscoveryDeviceView.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = models$0.DiscoveryTaskView.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = models$0.TopologyGraphView.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = discovery$0.VendorCommandProfile.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Array($$createType9);
const $$createType17 = models$0.TaskStartResponse.createFrom;
