// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService 发现任务服务 - 负责拓扑发现任务的管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CancelDiscovery 取消发现任务
 */
export function CancelDiscovery(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2827233845, taskID);
}

/**
 * GetCurrentDiscoveryTask 获取当前运行的任务ID
 */
export function GetCurrentDiscoveryTask(): $CancellablePromise<string> {
    return $Call.ByID(2205226273);
}

/**
 * GetRawOutput 获取原始命令输出
 */
export function GetRawOutput(taskID: string, deviceIP: string, commandKey: string): $CancellablePromise<string> {
    return $Call.ByID(3454866016, taskID, deviceIP, commandKey);
}

/**
 * GetSupportedVendors 获取支持的厂商列表
 */
export function GetSupportedVendors(): $CancellablePromise<string[]> {
    return $Call.ByID(3311268684).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetTaskDevices 获取任务下的设备列表
 */
export function GetTaskDevices(taskID: string): $CancellablePromise<discovery$0.DiscoveryDeviceView[]> {
    return $Call.ByID(870059783, taskID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTaskStatus 获取任务状态
 */
export function GetTaskStatus(taskID: string): $CancellablePromise<discovery$0.DiscoveryTaskView | null> {
    return $Call.ByID(1710880238, taskID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetVendorProfiles 获取所有厂商命令配置
 */
export function GetVendorProfiles(): $CancellablePromise<(discovery$0.VendorCommandProfile | null)[]> {
    return $Call.ByID(2906719573).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * IsDiscoveryRunning 检查是否有发现任务在运行
 */
export function IsDiscoveryRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3301156278);
}

/**
 * ListDiscoveryTasks 列出所有发现任务
 */
export function ListDiscoveryTasks(limit: number): $CancellablePromise<discovery$0.DiscoveryTaskView[]> {
    return $Call.ByID(3407912979, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * RetryFailedDevices 重试失败的设备
 */
export function RetryFailedDevices(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(610298369, taskID);
}

/**
 * StartDiscovery 启动发现任务
 */
export function StartDiscovery(req: discovery$0.StartDiscoveryRequest): $CancellablePromise<discovery$0.TaskStartResponse> {
    return $Call.ByID(2474301625, req).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.DiscoveryDeviceView.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.DiscoveryTaskView.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = discovery$0.VendorCommandProfile.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType3);
const $$createType9 = models$0.TaskStartResponse.createFrom;
