// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService 引擎控制服务 - 负责任务执行和状态管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as executor$0 from "../executor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * IsRunning 检查引擎是否正在运行
 */
export function IsRunning(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(271359178) as any;
    return $resultPromise;
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 */
export function ResolveSuspend(ip: string, action: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2096616055, ip, action) as any;
    return $resultPromise;
}

/**
 * ServiceStartup Wails 服务启动生命周期钩子
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(528566111, options) as any;
    return $resultPromise;
}

/**
 * StartBackup 启动核心备份动作
 */
export function StartBackup(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1249450791) as any;
    return $resultPromise;
}

/**
 * StartEngine 启动核心下发动作
 */
export function StartEngine(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(977891171) as any;
    return $resultPromise;
}

/**
 * StartEngineWithSelection 使用选定的设备和命令组启动引擎
 */
export function StartEngineWithSelection(deviceIPs: string[], commandGroupID: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2776463903, deviceIPs, commandGroupID) as any;
    return $resultPromise;
}

/**
 * WailsSuspendHandler 构建代理 Suspend 钩子替换原先的控制台询问方式
 */
export function WailsSuspendHandler(): Promise<executor$0.SuspendHandler> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1950080195) as any;
    return $resultPromise;
}
