// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService 引擎控制服务 - 负责任务执行和状态管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../report/models.js";

/**
 * GetExecutionSnapshot 获取当前执行的快照
 * 前端调用此方法获取完整的执行状态，无需前端计算
 */
export function GetExecutionSnapshot(): $CancellablePromise<report$0.ExecutionSnapshot | null> {
    return $Call.ByID(595539449).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsRunning 检查引擎是否正在运行（使用全局状态）
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(271359178);
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 * 委托给全局 SuspendManager 处理
 */
export function ResolveSuspend(sessionIDOrIP: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(2096616055, sessionIDOrIP, action);
}

/**
 * StartBackup 启动核心备份动作
 */
export function StartBackup(): $CancellablePromise<void> {
    return $Call.ByID(1249450791);
}

/**
 * StartEngine 启动核心下发动作
 */
export function StartEngine(): $CancellablePromise<void> {
    return $Call.ByID(977891171);
}

/**
 * StartEngineWithSelection 使用选定的设备和命令组启动引擎
 */
export function StartEngineWithSelection(deviceIPs: string[], commandGroupID: string): $CancellablePromise<void> {
    return $Call.ByID(2776463903, deviceIPs, commandGroupID);
}

/**
 * StopEngine 停止正在执行的任务
 */
export function StopEngine(): $CancellablePromise<void> {
    return $Call.ByID(2703249073);
}

// Private type creation functions
const $$createType0 = report$0.ExecutionSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
