// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionHistoryService 历史执行记录查询服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteExecutionRecord 删除历史执行记录
 */
export function DeleteExecutionRecord(id: string): $CancellablePromise<void> {
    return $Call.ByID(2777484439, id);
}

/**
 * GetExecutionRecord 根据 ID 获取历史执行记录详情
 */
export function GetExecutionRecord(id: string): $CancellablePromise<models$0.ExecutionRecord | null> {
    return $Call.ByID(2763900808, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetExecutionRecordStats 获取执行记录统计信息
 */
export function GetExecutionRecordStats(taskGroupID: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3514580747, taskGroupID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetModeList 获取所有可用的执行模式列表
 */
export function GetModeList(): $CancellablePromise<string[]> {
    return $Call.ByID(2245651898).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRunnerSourceList 获取所有可用的执行来源列表
 */
export function GetRunnerSourceList(): $CancellablePromise<string[]> {
    return $Call.ByID(3543765262).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStatusList 获取所有可用的状态列表
 */
export function GetStatusList(): $CancellablePromise<string[]> {
    return $Call.ByID(1737169275).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListExecutionRecords 查询历史执行记录列表
 */
export function ListExecutionRecords(req: $models.ListExecutionRecordsRequest): $CancellablePromise<$models.ListExecutionRecordsResponse | null> {
    return $Call.ByID(724976359, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenFileWithDefaultApp 使用系统默认应用打开文件
 */
export function OpenFileWithDefaultApp(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(4184946633, filePath);
}

// Private type creation functions
const $$createType0 = models$0.ExecutionRecord.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.ListExecutionRecordsResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
