// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ForgeService 配置构建服务 (Wails Binding)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as forge$0 from "../forge/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildConfig 构建配置 (Wails Binding)
 * 前端调用此方法执行配置生成
 */
export function BuildConfig(req: forge$0.BuildRequest | null): $CancellablePromise<forge$0.BuildResult | null> {
    return $Call.ByID(3357362024, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CalculateIPv4 IPv4 网络信息与子网划分计算。
 */
export function CalculateIPv4(req: $models.IPv4CalcRequest): $CancellablePromise<$models.IPv4CalcResult | null> {
    return $Call.ByID(325126253, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CalculateIPv6 IPv6 网络信息、包含关系与子网划分计算。
 */
export function CalculateIPv6(req: $models.IPv6CalcRequest): $CancellablePromise<$models.IPv6CalcResult | null> {
    return $Call.ByID(291571015, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DetectBindingMode 检测是否为绑定模式 (Wails Binding)
 * 模板第一行包含 [BindingDeviceIP] 时为绑定模式
 */
export function DetectBindingMode(template: string): $CancellablePromise<boolean> {
    return $Call.ByID(3072450605, template);
}

/**
 * ExpandValues 展开变量值 (Wails Binding)
 * 前端调用此方法预览语法糖展开结果
 */
export function ExpandValues(req: forge$0.ExpandRequest | null): $CancellablePromise<forge$0.ExpandResult | null> {
    return $Call.ByID(3126028648, req).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ExportIPv4SubnetsCSV 导出 IPv4 子网划分 CSV（后端生成内容，前端仅触发下载）。
 */
export function ExportIPv4SubnetsCSV(req: $models.IPv4CalcRequest): $CancellablePromise<$models.IPv4SubnetCSVResult | null> {
    return $Call.ByID(2255730601, req).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GenerateBindingPreview 生成绑定模式预览 (Wails Binding)
 */
export function GenerateBindingPreview(template: string, variables: forge$0.VarInput[]): $CancellablePromise<$models.BindingPreview[]> {
    return $Call.ByID(3138174978, template, variables).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ParseIPRange 解析IP范围语法 (Wails Binding)
 * 支持格式: "192.168.1.10-20" -> {start: "192.168.1.10", end: "192.168.1.20", count: 11}
 */
export function ParseIPRange(ipRange: string): $CancellablePromise<$models.IPRangeResult | null> {
    return $Call.ByID(3033366997, ipRange).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ValidateIP 验证IP格式 (Wails Binding)
 * 支持 IPv4 和 IPv6 格式验证
 */
export function ValidateIP(ip: string): $CancellablePromise<$models.ForgeIPValidationResult | null> {
    return $Call.ByID(633841705, ip).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ValidateIPs 批量验证IP (Wails Binding)
 * 输入逗号或换行分隔的IP字符串，返回验证结果
 */
export function ValidateIPs(ipString: string): $CancellablePromise<$models.IPsValidationResult | null> {
    return $Call.ByID(3545105838, ipString).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = forge$0.BuildResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.IPv4CalcResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.IPv6CalcResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = forge$0.ExpandResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.IPv4SubnetCSVResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.BindingPreview.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.IPRangeResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.ForgeIPValidationResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.IPsValidationResult.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
