// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * BindingPreview 绑定预览结果
 */
export class BindingPreview {
    /**
     * IP地址
     */
    "ip": string;

    /**
     * 对应的命令
     */
    "commands": string;

    /** Creates a new BindingPreview instance. */
    constructor($$source: Partial<BindingPreview> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BindingPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): BindingPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BindingPreview($$parsedSource as Partial<BindingPreview>);
    }
}

/**
 * ForgeIPValidationResult IP验证结果（Forge专用）
 */
export class ForgeIPValidationResult {
    /**
     * 是否有效
     */
    "isValid": boolean;

    /**
     * IP类型: "IPv4", "IPv6", ""
     */
    "type": string;

    /**
     * 提示信息
     */
    "message": string;

    /** Creates a new ForgeIPValidationResult instance. */
    constructor($$source: Partial<ForgeIPValidationResult> = {}) {
        if (!("isValid" in $$source)) {
            this["isValid"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForgeIPValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ForgeIPValidationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForgeIPValidationResult($$parsedSource as Partial<ForgeIPValidationResult>);
    }
}

/**
 * IPRangeResult IP范围解析结果
 */
export class IPRangeResult {
    /**
     * 是否有效
     */
    "isValid": boolean;

    /**
     * 起始IP
     */
    "start": string;

    /**
     * 结束IP
     */
    "end": string;

    /**
     * IP数量
     */
    "count": number;

    /**
     * IP列表
     */
    "list": string[];

    /**
     * 提示信息
     */
    "message": string;

    /** Creates a new IPRangeResult instance. */
    constructor($$source: Partial<IPRangeResult> = {}) {
        if (!("isValid" in $$source)) {
            this["isValid"] = false;
        }
        if (!("start" in $$source)) {
            this["start"] = "";
        }
        if (!("end" in $$source)) {
            this["end"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("list" in $$source)) {
            this["list"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPRangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPRangeResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField4_0($$parsedSource["list"]);
        }
        return new IPRangeResult($$parsedSource as Partial<IPRangeResult>);
    }
}

/**
 * IPsValidationResult 批量IP验证结果
 */
export class IPsValidationResult {
    /**
     * 有效IP数量
     */
    "validCount": number;

    /**
     * 无效IP数量
     */
    "invalidCount": number;

    /**
     * 有效IP列表
     */
    "validIPs": string[];

    /**
     * 无效IP列表
     */
    "invalidIPs": string[];

    /** Creates a new IPsValidationResult instance. */
    constructor($$source: Partial<IPsValidationResult> = {}) {
        if (!("validCount" in $$source)) {
            this["validCount"] = 0;
        }
        if (!("invalidCount" in $$source)) {
            this["invalidCount"] = 0;
        }
        if (!("validIPs" in $$source)) {
            this["validIPs"] = [];
        }
        if (!("invalidIPs" in $$source)) {
            this["invalidIPs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPsValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPsValidationResult {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("validIPs" in $$parsedSource) {
            $$parsedSource["validIPs"] = $$createField2_0($$parsedSource["validIPs"]);
        }
        if ("invalidIPs" in $$parsedSource) {
            $$parsedSource["invalidIPs"] = $$createField3_0($$parsedSource["invalidIPs"]);
        }
        return new IPsValidationResult($$parsedSource as Partial<IPsValidationResult>);
    }
}

/**
 * IPv4CalcRequest IPv4 计算请求。
 */
export class IPv4CalcRequest {
    "ip": string;
    "mask": string;
    "hostCount": string;
    "subnetCount": string;
    "forceDisplayAllSubnets": boolean;

    /** Creates a new IPv4CalcRequest instance. */
    constructor($$source: Partial<IPv4CalcRequest> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("mask" in $$source)) {
            this["mask"] = "";
        }
        if (!("hostCount" in $$source)) {
            this["hostCount"] = "";
        }
        if (!("subnetCount" in $$source)) {
            this["subnetCount"] = "";
        }
        if (!("forceDisplayAllSubnets" in $$source)) {
            this["forceDisplayAllSubnets"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv4CalcRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv4CalcRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv4CalcRequest($$parsedSource as Partial<IPv4CalcRequest>);
    }
}

/**
 * IPv4CalcResult IPv4 计算结果。
 */
export class IPv4CalcResult {
    "baseError": string;
    "baseRecords": NetworkRecord[];
    "subnetError": string;
    "subnetWarning": string;
    "showForceButton": boolean;
    "subnets": IPv4SubnetItem[];
    "totalSubnets": number;

    /** Creates a new IPv4CalcResult instance. */
    constructor($$source: Partial<IPv4CalcResult> = {}) {
        if (!("baseError" in $$source)) {
            this["baseError"] = "";
        }
        if (!("baseRecords" in $$source)) {
            this["baseRecords"] = [];
        }
        if (!("subnetError" in $$source)) {
            this["subnetError"] = "";
        }
        if (!("subnetWarning" in $$source)) {
            this["subnetWarning"] = "";
        }
        if (!("showForceButton" in $$source)) {
            this["showForceButton"] = false;
        }
        if (!("subnets" in $$source)) {
            this["subnets"] = [];
        }
        if (!("totalSubnets" in $$source)) {
            this["totalSubnets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv4CalcResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv4CalcResult {
        const $$createField1_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseRecords" in $$parsedSource) {
            $$parsedSource["baseRecords"] = $$createField1_0($$parsedSource["baseRecords"]);
        }
        if ("subnets" in $$parsedSource) {
            $$parsedSource["subnets"] = $$createField5_0($$parsedSource["subnets"]);
        }
        return new IPv4CalcResult($$parsedSource as Partial<IPv4CalcResult>);
    }
}

/**
 * IPv4SubnetCSVResult IPv4 子网 CSV 导出结果。
 */
export class IPv4SubnetCSVResult {
    "fileName": string;
    "content": string;

    /** Creates a new IPv4SubnetCSVResult instance. */
    constructor($$source: Partial<IPv4SubnetCSVResult> = {}) {
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv4SubnetCSVResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv4SubnetCSVResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv4SubnetCSVResult($$parsedSource as Partial<IPv4SubnetCSVResult>);
    }
}

/**
 * IPv4SubnetItem IPv4 子网条目。
 */
export class IPv4SubnetItem {
    "index": number;
    "network": string;
    "cidr": number;
    "firstUsable": string;
    "lastUsable": string;
    "broadcast": string;
    "mask": string;

    /** Creates a new IPv4SubnetItem instance. */
    constructor($$source: Partial<IPv4SubnetItem> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("cidr" in $$source)) {
            this["cidr"] = 0;
        }
        if (!("firstUsable" in $$source)) {
            this["firstUsable"] = "";
        }
        if (!("lastUsable" in $$source)) {
            this["lastUsable"] = "";
        }
        if (!("broadcast" in $$source)) {
            this["broadcast"] = "";
        }
        if (!("mask" in $$source)) {
            this["mask"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv4SubnetItem instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv4SubnetItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv4SubnetItem($$parsedSource as Partial<IPv4SubnetItem>);
    }
}

/**
 * IPv6CalcRequest IPv6 计算请求。
 */
export class IPv6CalcRequest {
    "ip": string;
    "prefix": string;
    "checkIp": string;
    "newPrefix": string;

    /** Creates a new IPv6CalcRequest instance. */
    constructor($$source: Partial<IPv6CalcRequest> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("checkIp" in $$source)) {
            this["checkIp"] = "";
        }
        if (!("newPrefix" in $$source)) {
            this["newPrefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv6CalcRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv6CalcRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv6CalcRequest($$parsedSource as Partial<IPv6CalcRequest>);
    }
}

/**
 * IPv6CalcResult IPv6 计算结果。
 */
export class IPv6CalcResult {
    "baseError": string;
    "baseRecords": NetworkRecord[];
    "inclusionCheck"?: IPv6InclusionResult | null;
    "subnetError": string;
    "subnetWarning": string;
    "subnets": IPv6SubnetItem[];
    "totalSubnets": number;

    /** Creates a new IPv6CalcResult instance. */
    constructor($$source: Partial<IPv6CalcResult> = {}) {
        if (!("baseError" in $$source)) {
            this["baseError"] = "";
        }
        if (!("baseRecords" in $$source)) {
            this["baseRecords"] = [];
        }
        if (!("subnetError" in $$source)) {
            this["subnetError"] = "";
        }
        if (!("subnetWarning" in $$source)) {
            this["subnetWarning"] = "";
        }
        if (!("subnets" in $$source)) {
            this["subnets"] = [];
        }
        if (!("totalSubnets" in $$source)) {
            this["totalSubnets"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv6CalcResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv6CalcResult {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseRecords" in $$parsedSource) {
            $$parsedSource["baseRecords"] = $$createField1_0($$parsedSource["baseRecords"]);
        }
        if ("inclusionCheck" in $$parsedSource) {
            $$parsedSource["inclusionCheck"] = $$createField2_0($$parsedSource["inclusionCheck"]);
        }
        if ("subnets" in $$parsedSource) {
            $$parsedSource["subnets"] = $$createField5_0($$parsedSource["subnets"]);
        }
        return new IPv6CalcResult($$parsedSource as Partial<IPv6CalcResult>);
    }
}

/**
 * IPv6InclusionResult IPv6 包含关系检查结果。
 */
export class IPv6InclusionResult {
    "isIncluded": boolean;
    "message": string;

    /** Creates a new IPv6InclusionResult instance. */
    constructor($$source: Partial<IPv6InclusionResult> = {}) {
        if (!("isIncluded" in $$source)) {
            this["isIncluded"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv6InclusionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv6InclusionResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv6InclusionResult($$parsedSource as Partial<IPv6InclusionResult>);
    }
}

/**
 * IPv6SubnetItem IPv6 子网条目。
 */
export class IPv6SubnetItem {
    "index": number;
    "network": string;
    "cidr": number;
    "isIncluded": boolean;

    /** Creates a new IPv6SubnetItem instance. */
    constructor($$source: Partial<IPv6SubnetItem> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("network" in $$source)) {
            this["network"] = "";
        }
        if (!("cidr" in $$source)) {
            this["cidr"] = 0;
        }
        if (!("isIncluded" in $$source)) {
            this["isIncluded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPv6SubnetItem instance from a string or object.
     */
    static createFrom($$source: any = {}): IPv6SubnetItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IPv6SubnetItem($$parsedSource as Partial<IPv6SubnetItem>);
    }
}

/**
 * ListExecutionRecordsRequest 列表查询请求
 */
export class ListExecutionRecordsRequest {
    "taskGroupId": string;
    "runnerSource": string;
    "status": string;
    "page": number;
    "pageSize": number;
    "sortBy": string;
    "sortOrder": string;

    /** Creates a new ListExecutionRecordsRequest instance. */
    constructor($$source: Partial<ListExecutionRecordsRequest> = {}) {
        if (!("taskGroupId" in $$source)) {
            this["taskGroupId"] = "";
        }
        if (!("runnerSource" in $$source)) {
            this["runnerSource"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListExecutionRecordsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListExecutionRecordsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListExecutionRecordsRequest($$parsedSource as Partial<ListExecutionRecordsRequest>);
    }
}

/**
 * ListExecutionRecordsResponse 列表查询响应
 */
export class ListExecutionRecordsResponse {
    "data": config$0.ExecutionRecord[];
    "total": number;
    "page": number;
    "pageSize": number;
    "totalPages": number;

    /** Creates a new ListExecutionRecordsResponse instance. */
    constructor($$source: Partial<ListExecutionRecordsResponse> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListExecutionRecordsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ListExecutionRecordsResponse {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new ListExecutionRecordsResponse($$parsedSource as Partial<ListExecutionRecordsResponse>);
    }
}

/**
 * NetworkRecord 通用标签值记录，供前端直接渲染。
 */
export class NetworkRecord {
    "label": string;
    "value": string;

    /** Creates a new NetworkRecord instance. */
    constructor($$source: Partial<NetworkRecord> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkRecord {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkRecord($$parsedSource as Partial<NetworkRecord>);
    }
}

/**
 * QueryOptions 通用查询条件
 * 用于设备列表、任务列表等分页查询
 */
export class QueryOptions {
    /**
     * 搜索关键词
     */
    "searchQuery": string;

    /**
     * 搜索字段 (如 group, ip, tag)
     */
    "filterField": string;

    /**
     * 过滤值 (如 status=running)
     */
    "filterValue": string;

    /**
     * 页码 (1-based)
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 排序字段
     */
    "sortBy": string;

    /**
     * 排序方向: asc/desc
     */
    "sortOrder": string;

    /** Creates a new QueryOptions instance. */
    constructor($$source: Partial<QueryOptions> = {}) {
        if (!("searchQuery" in $$source)) {
            this["searchQuery"] = "";
        }
        if (!("filterField" in $$source)) {
            this["filterField"] = "";
        }
        if (!("filterValue" in $$source)) {
            this["filterValue"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryOptions($$parsedSource as Partial<QueryOptions>);
    }
}

/**
 * QueryResult 分页查询结果
 */
export class QueryResult {
    /**
     * 数据列表
     */
    "data": any;

    /**
     * 总记录数
     */
    "total": number;

    /**
     * 当前页码
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 总页数
     */
    "totalPages": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = null;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * RuntimeConfigData 运行时配置数据结构（用于Wails绑定）
 */
export class RuntimeConfigData {
    "timeouts": {"command": number, "connection": number, "handshake": number, "shortCmd": number, "longCmd": number};
    "limits": {"maxLogsPerDevice": number, "maxLogLength": number, "logTruncateThreshold": number, "maxConcurrentDevices": number};
    "engine": {"workerCount": number, "eventBufferSize": number, "fallbackEventCapacity": number};
    "buffers": {"defaultSize": number, "smallSize": number, "largeSize": number};
    "pagination": {"lineThreshold": number, "checkInterval": number};

    /** Creates a new RuntimeConfigData instance. */
    constructor($$source: Partial<RuntimeConfigData> = {}) {
        if (!("timeouts" in $$source)) {
            this["timeouts"] = {"command": 0, "connection": 0, "handshake": 0, "shortCmd": 0, "longCmd": 0};
        }
        if (!("limits" in $$source)) {
            this["limits"] = {"maxLogsPerDevice": 0, "maxLogLength": 0, "logTruncateThreshold": 0, "maxConcurrentDevices": 0};
        }
        if (!("engine" in $$source)) {
            this["engine"] = {"workerCount": 0, "eventBufferSize": 0, "fallbackEventCapacity": 0};
        }
        if (!("buffers" in $$source)) {
            this["buffers"] = {"defaultSize": 0, "smallSize": 0, "largeSize": 0};
        }
        if (!("pagination" in $$source)) {
            this["pagination"] = {"lineThreshold": 0, "checkInterval": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfigData instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeConfigData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeConfigData($$parsedSource as Partial<RuntimeConfigData>);
    }
}

/**
 * SSHAlgorithmOption SSH 算法候选项
 */
export class SSHAlgorithmOption {
    "name": string;

    /**
     * "secure" | "insecure"
     */
    "security": string;

    /**
     * "supported" | "insecure"
     */
    "source": string;

    /** Creates a new SSHAlgorithmOption instance. */
    constructor($$source: Partial<SSHAlgorithmOption> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("security" in $$source)) {
            this["security"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAlgorithmOption instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAlgorithmOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHAlgorithmOption($$parsedSource as Partial<SSHAlgorithmOption>);
    }
}

/**
 * SSHAlgorithmOptions SSH 算法候选集合
 */
export class SSHAlgorithmOptions {
    "ciphers": SSHAlgorithmOption[];
    "keyExchanges": SSHAlgorithmOption[];
    "macs": SSHAlgorithmOption[];
    "hostKeyAlgorithms": SSHAlgorithmOption[];

    /** Creates a new SSHAlgorithmOptions instance. */
    constructor($$source: Partial<SSHAlgorithmOptions> = {}) {
        if (!("ciphers" in $$source)) {
            this["ciphers"] = [];
        }
        if (!("keyExchanges" in $$source)) {
            this["keyExchanges"] = [];
        }
        if (!("macs" in $$source)) {
            this["macs"] = [];
        }
        if (!("hostKeyAlgorithms" in $$source)) {
            this["hostKeyAlgorithms"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAlgorithmOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAlgorithmOptions {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField0_0($$parsedSource["ciphers"]);
        }
        if ("keyExchanges" in $$parsedSource) {
            $$parsedSource["keyExchanges"] = $$createField1_0($$parsedSource["keyExchanges"]);
        }
        if ("macs" in $$parsedSource) {
            $$parsedSource["macs"] = $$createField2_0($$parsedSource["macs"]);
        }
        if ("hostKeyAlgorithms" in $$parsedSource) {
            $$parsedSource["hostKeyAlgorithms"] = $$createField3_0($$parsedSource["hostKeyAlgorithms"]);
        }
        return new SSHAlgorithmOptions($$parsedSource as Partial<SSHAlgorithmOptions>);
    }
}

/**
 * TaskCommandOverview 任务命令信息概览
 */
export class TaskCommandOverview {
    "id": number;
    "name": string;
    "description": string;
    "commands": string[];
    "missing": boolean;

    /** Creates a new TaskCommandOverview instance. */
    constructor($$source: Partial<TaskCommandOverview> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskCommandOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskCommandOverview {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        return new TaskCommandOverview($$parsedSource as Partial<TaskCommandOverview>);
    }
}

/**
 * TaskDeviceOverview 任务关联设备概览
 */
export class TaskDeviceOverview {
    "id": number;
    "ip": string;
    "group": string;
    "tags": string[];
    "missing": boolean;

    /** Creates a new TaskDeviceOverview instance. */
    constructor($$source: Partial<TaskDeviceOverview> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskDeviceOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskDeviceOverview {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new TaskDeviceOverview($$parsedSource as Partial<TaskDeviceOverview>);
    }
}

/**
 * TaskGroupDetailViewModel 任务详情聚合模型
 * 为执行大屏详情/编辑弹窗提供后端解析后的结构化数据
 */
export class TaskGroupDetailViewModel {
    "task": models$0.TaskGroup;
    "itemCount": number;
    "canEdit": boolean;
    "editDisabledReason": string;
    "items": TaskGroupItemDetailViewModel[];
    "missingDevices": number[];
    "missingCommandIds": number[];

    /** Creates a new TaskGroupDetailViewModel instance. */
    constructor($$source: Partial<TaskGroupDetailViewModel> = {}) {
        if (!("task" in $$source)) {
            this["task"] = (new models$0.TaskGroup());
        }
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }
        if (!("canEdit" in $$source)) {
            this["canEdit"] = false;
        }
        if (!("editDisabledReason" in $$source)) {
            this["editDisabledReason"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("missingDevices" in $$source)) {
            this["missingDevices"] = [];
        }
        if (!("missingCommandIds" in $$source)) {
            this["missingCommandIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroupDetailViewModel instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskGroupDetailViewModel {
        const $$createField0_0 = $$createType13;
        const $$createField4_0 = $$createType15;
        const $$createField5_0 = $$createType16;
        const $$createField6_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField0_0($$parsedSource["task"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField4_0($$parsedSource["items"]);
        }
        if ("missingDevices" in $$parsedSource) {
            $$parsedSource["missingDevices"] = $$createField5_0($$parsedSource["missingDevices"]);
        }
        if ("missingCommandIds" in $$parsedSource) {
            $$parsedSource["missingCommandIds"] = $$createField6_0($$parsedSource["missingCommandIds"]);
        }
        return new TaskGroupDetailViewModel($$parsedSource as Partial<TaskGroupDetailViewModel>);
    }
}

/**
 * TaskGroupItemDetailViewModel 单个任务项详情
 */
export class TaskGroupItemDetailViewModel {
    "index": number;
    "mode": string;
    "deviceCount": number;
    "devices": TaskDeviceOverview[];
    "commandInfo"?: TaskCommandOverview | null;
    "commands": string[];

    /** Creates a new TaskGroupItemDetailViewModel instance. */
    constructor($$source: Partial<TaskGroupItemDetailViewModel> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("deviceCount" in $$source)) {
            this["deviceCount"] = 0;
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroupItemDetailViewModel instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskGroupItemDetailViewModel {
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField3_0($$parsedSource["devices"]);
        }
        if ("commandInfo" in $$parsedSource) {
            $$parsedSource["commandInfo"] = $$createField4_0($$parsedSource["commandInfo"]);
        }
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField5_0($$parsedSource["commands"]);
        }
        return new TaskGroupItemDetailViewModel($$parsedSource as Partial<TaskGroupItemDetailViewModel>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = NetworkRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = IPv4SubnetItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = IPv6InclusionResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = IPv6SubnetItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = config$0.ExecutionRecord.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SSHAlgorithmOption.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = models$0.TaskGroup.createFrom;
const $$createType14 = TaskGroupItemDetailViewModel.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = TaskDeviceOverview.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = TaskCommandOverview.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
