// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * BindingPreview 绑定预览结果
 */
export class BindingPreview {
    /**
     * IP地址
     */
    "ip": string;

    /**
     * 对应的命令
     */
    "commands": string;

    /** Creates a new BindingPreview instance. */
    constructor($$source: Partial<BindingPreview> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BindingPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): BindingPreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BindingPreview($$parsedSource as Partial<BindingPreview>);
    }
}

/**
 * ForgeIPValidationResult IP验证结果（Forge专用）
 */
export class ForgeIPValidationResult {
    /**
     * 是否有效
     */
    "isValid": boolean;

    /**
     * IP类型: "IPv4", "IPv6", ""
     */
    "type": string;

    /**
     * 提示信息
     */
    "message": string;

    /** Creates a new ForgeIPValidationResult instance. */
    constructor($$source: Partial<ForgeIPValidationResult> = {}) {
        if (!("isValid" in $$source)) {
            this["isValid"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForgeIPValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ForgeIPValidationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForgeIPValidationResult($$parsedSource as Partial<ForgeIPValidationResult>);
    }
}

/**
 * IPRangeResult IP范围解析结果
 */
export class IPRangeResult {
    /**
     * 是否有效
     */
    "isValid": boolean;

    /**
     * 起始IP
     */
    "start": string;

    /**
     * 结束IP
     */
    "end": string;

    /**
     * IP数量
     */
    "count": number;

    /**
     * IP列表
     */
    "list": string[];

    /**
     * 提示信息
     */
    "message": string;

    /** Creates a new IPRangeResult instance. */
    constructor($$source: Partial<IPRangeResult> = {}) {
        if (!("isValid" in $$source)) {
            this["isValid"] = false;
        }
        if (!("start" in $$source)) {
            this["start"] = "";
        }
        if (!("end" in $$source)) {
            this["end"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("list" in $$source)) {
            this["list"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPRangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPRangeResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField4_0($$parsedSource["list"]);
        }
        return new IPRangeResult($$parsedSource as Partial<IPRangeResult>);
    }
}

/**
 * IPsValidationResult 批量IP验证结果
 */
export class IPsValidationResult {
    /**
     * 有效IP数量
     */
    "validCount": number;

    /**
     * 无效IP数量
     */
    "invalidCount": number;

    /**
     * 有效IP列表
     */
    "validIPs": string[];

    /**
     * 无效IP列表
     */
    "invalidIPs": string[];

    /** Creates a new IPsValidationResult instance. */
    constructor($$source: Partial<IPsValidationResult> = {}) {
        if (!("validCount" in $$source)) {
            this["validCount"] = 0;
        }
        if (!("invalidCount" in $$source)) {
            this["invalidCount"] = 0;
        }
        if (!("validIPs" in $$source)) {
            this["validIPs"] = [];
        }
        if (!("invalidIPs" in $$source)) {
            this["invalidIPs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IPsValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IPsValidationResult {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("validIPs" in $$parsedSource) {
            $$parsedSource["validIPs"] = $$createField2_0($$parsedSource["validIPs"]);
        }
        if ("invalidIPs" in $$parsedSource) {
            $$parsedSource["invalidIPs"] = $$createField3_0($$parsedSource["invalidIPs"]);
        }
        return new IPsValidationResult($$parsedSource as Partial<IPsValidationResult>);
    }
}

/**
 * QueryOptions 通用查询条件
 * 用于设备列表、任务列表等分页查询
 */
export class QueryOptions {
    /**
     * 搜索关键词
     */
    "searchQuery": string;

    /**
     * 搜索字段 (如 group, ip, tag)
     */
    "filterField": string;

    /**
     * 过滤值 (如 status=running)
     */
    "filterValue": string;

    /**
     * 页码 (1-based)
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 排序字段
     */
    "sortBy": string;

    /**
     * 排序方向: asc/desc
     */
    "sortOrder": string;

    /** Creates a new QueryOptions instance. */
    constructor($$source: Partial<QueryOptions> = {}) {
        if (!("searchQuery" in $$source)) {
            this["searchQuery"] = "";
        }
        if (!("filterField" in $$source)) {
            this["filterField"] = "";
        }
        if (!("filterValue" in $$source)) {
            this["filterValue"] = "";
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryOptions($$parsedSource as Partial<QueryOptions>);
    }
}

/**
 * QueryResult 分页查询结果
 */
export class QueryResult {
    /**
     * 数据列表
     */
    "data": any;

    /**
     * 总记录数
     */
    "total": number;

    /**
     * 当前页码
     */
    "page": number;

    /**
     * 每页条数
     */
    "pageSize": number;

    /**
     * 总页数
     */
    "totalPages": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = null;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * RuntimeConfigData 运行时配置数据结构（用于Wails绑定）
 */
export class RuntimeConfigData {
    "timeouts": {"command": number, "connection": number, "handshake": number, "shortCmd": number, "longCmd": number};
    "limits": {"maxLogsPerDevice": number, "maxLogLength": number, "logTruncateThreshold": number, "maxConcurrentDevices": number};
    "engine": {"workerCount": number, "eventBufferSize": number, "fallbackEventCapacity": number};
    "buffers": {"defaultSize": number, "smallSize": number, "largeSize": number};
    "pagination": {"lineThreshold": number, "checkInterval": number};

    /** Creates a new RuntimeConfigData instance. */
    constructor($$source: Partial<RuntimeConfigData> = {}) {
        if (!("timeouts" in $$source)) {
            this["timeouts"] = {"command": 0, "connection": 0, "handshake": 0, "shortCmd": 0, "longCmd": 0};
        }
        if (!("limits" in $$source)) {
            this["limits"] = {"maxLogsPerDevice": 0, "maxLogLength": 0, "logTruncateThreshold": 0, "maxConcurrentDevices": 0};
        }
        if (!("engine" in $$source)) {
            this["engine"] = {"workerCount": 0, "eventBufferSize": 0, "fallbackEventCapacity": 0};
        }
        if (!("buffers" in $$source)) {
            this["buffers"] = {"defaultSize": 0, "smallSize": 0, "largeSize": 0};
        }
        if (!("pagination" in $$source)) {
            this["pagination"] = {"lineThreshold": 0, "checkInterval": 0};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeConfigData instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeConfigData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeConfigData($$parsedSource as Partial<RuntimeConfigData>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
