// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlanCompareService 规划比对服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Compare 执行规划比对。
 */
export function Compare(taskID: string, planID: string): $CancellablePromise<models$0.CompareResult | null> {
    return $Call.ByID(3748315670, taskID, planID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExportDiffReport 导出差异报告（json/csv）。
 */
export function ExportDiffReport(reportID: string, format: string): $CancellablePromise<string> {
    return $Call.ByID(2298011856, reportID, format);
}

/**
 * GetCompareResult 获取差异报告明细。
 */
export function GetCompareResult(reportID: string): $CancellablePromise<models$0.CompareResult | null> {
    return $Call.ByID(1740070905, reportID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDiffReport 获取差异报告摘要。
 */
export function GetDiffReport(reportID: string): $CancellablePromise<models$0.DiffReportView | null> {
    return $Call.ByID(1406594972, reportID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ImportPlanExcel 导入规划Excel。
 */
export function ImportPlanExcel(filePath: string): $CancellablePromise<models$0.PlanImportResult | null> {
    return $Call.ByID(1063366568, filePath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListPlanFiles 列出已导入规划文件。
 */
export function ListPlanFiles(limit: number): $CancellablePromise<models$0.PlanUploadView[]> {
    return $Call.ByID(291493559, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.CompareResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.DiffReportView.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.PlanImportResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.PlanUploadView.createFrom;
const $$createType7 = $Create.Array($$createType6);
