// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService 查询服务 - 提供带条件的列表查询
 * 前端无需本地过滤，直接调用后端查询接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDeviceGroups 获取所有设备分组名称（用于前端下拉选项）
 */
export function GetDeviceGroups(): $CancellablePromise<string[]> {
    return $Call.ByID(3486201921).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetDeviceTags 获取所有设备标签（用于前端下拉选项）
 */
export function GetDeviceTags(): $CancellablePromise<string[]> {
    return $Call.ByID(2161320188).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListCommandGroups 查询命令组列表（支持搜索、过滤、分页）
 */
export function ListCommandGroups(opts: $models.QueryOptions): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(3365044130, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListDevices 查询设备列表（使用 Repository 分页查询）
 */
export function ListDevices(opts: $models.QueryOptions): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(2076140864, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListTaskGroups 查询任务组列表（支持搜索、过滤、分页）
 */
export function ListTaskGroups(opts: $models.QueryOptions): $CancellablePromise<$models.QueryResult | null> {
    return $Call.ByID(1904256516, opts).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.QueryResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
