// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置管理服务 - 负责全局配置的加载和保存
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * EnsureConfig 检查必需配置文件并返回是否有文件遗漏，以便前端提示
 */
export function EnsureConfig(): Promise<[config$0.DeviceAsset[], string[], string[]]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2867805956) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType2($result[1]);
        $result[2] = $$createType2($result[2]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * GetAppInfo 获取应用信息
 */
export function GetAppInfo(): Promise<{ [_: string]: string }> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2108623295) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType3($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * LoadSettings 获取合并后的主配置
 */
export function LoadSettings(): Promise<config$0.GlobalSettings | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3565402469) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType5($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * LogError 记录错误日志（前端调用）
 */
export function LogError(category: string, ip: string, message: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(474104816, category, ip, message) as any;
    return $resultPromise;
}

/**
 * LogInfo 记录信息日志（前端调用）
 */
export function LogInfo(category: string, ip: string, message: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1945591606, category, ip, message) as any;
    return $resultPromise;
}

/**
 * LogWarn 记录警告日志（前端调用）
 */
export function LogWarn(category: string, ip: string, message: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1210498838, category, ip, message) as any;
    return $resultPromise;
}

/**
 * SaveSettings 保存全局设置到配置文件
 */
export function SaveSettings(settings: config$0.GlobalSettings): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3400930556, settings) as any;
    return $resultPromise;
}

/**
 * ServiceStartup Wails 服务启动生命周期钩子
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1962381768, options) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = config$0.DeviceAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = config$0.GlobalSettings.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
