// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 设置管理服务 - 负责全局配置的加载和保存
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnsureConfig 返回当前数据库中的设备资产和默认命令组，供首页展示概况
 */
export function EnsureConfig(): $CancellablePromise<[config$0.DeviceAsset[], string[]]> {
    return $Call.ByID(2867805956).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        $result[1] = $$createType2($result[1]);
        return $result;
    });
}

/**
 * GetAppInfo 获取应用信息
 */
export function GetAppInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2108623295).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetRuntimeConfig 获取运行时配置
 */
export function GetRuntimeConfig(): $CancellablePromise<$models.RuntimeConfigData> {
    return $Call.ByID(3968671906).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * LoadSettings 获取合并后的主配置
 */
export function LoadSettings(): $CancellablePromise<config$0.GlobalSettings | null> {
    return $Call.ByID(3565402469).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * LogError 记录错误日志（前端调用）
 */
export function LogError(category: string, ip: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(474104816, category, ip, message);
}

/**
 * LogInfo 记录信息日志（前端调用）
 */
export function LogInfo(category: string, ip: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1945591606, category, ip, message);
}

/**
 * LogWarn 记录警告日志（前端调用）
 */
export function LogWarn(category: string, ip: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(1210498838, category, ip, message);
}

/**
 * ResetRuntimeConfigToDefault 重置运行时配置为默认值
 */
export function ResetRuntimeConfigToDefault(): $CancellablePromise<void> {
    return $Call.ByID(4262020943);
}

/**
 * SaveSettings 保存全局设置到配置文件
 */
export function SaveSettings(settings: config$0.GlobalSettings): $CancellablePromise<void> {
    return $Call.ByID(3400930556, settings);
}

/**
 * UpdateRuntimeConfig 更新运行时配置（热更新）
 */
export function UpdateRuntimeConfig(data: $models.RuntimeConfigData): $CancellablePromise<void> {
    return $Call.ByID(114110761, data);
}

// Private type creation functions
const $$createType0 = config$0.DeviceAsset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.RuntimeConfigData.createFrom;
const $$createType5 = config$0.GlobalSettings.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
