// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskGroupService 任务组管理服务 - 负责任务组的增删改查和执行
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTaskGroup 创建新任务组
 */
export function CreateTaskGroup(group: models$0.TaskGroup): $CancellablePromise<models$0.TaskGroup | null> {
    return $Call.ByID(3399746419, group).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteTaskGroup 删除任务组
 */
export function DeleteTaskGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(2162302226, id);
}

/**
 * GetTaskGroup 根据 ID 获取单个任务组
 */
export function GetTaskGroup(id: number): $CancellablePromise<models$0.TaskGroup | null> {
    return $Call.ByID(2623601141, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTaskGroupDetail 根据 ID 获取任务详情聚合信息
 */
export function GetTaskGroupDetail(id: number): $CancellablePromise<$models.TaskGroupDetailViewModel | null> {
    return $Call.ByID(759913924, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTaskGroups 获取所有任务组列表
 */
export function ListTaskGroups(): $CancellablePromise<models$0.TaskGroup[]> {
    return $Call.ByID(3904305468).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 * 委托给全局 SuspendManager 处理
 */
export function ResolveSuspend(sessionIDOrIP: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(4170877605, sessionIDOrIP, action);
}

/**
 * StartTaskGroup 启动任务组执行（并行执行模式）
 */
export function StartTaskGroup(id: number): $CancellablePromise<void> {
    return $Call.ByID(3072082837, id);
}

/**
 * UpdateTaskGroup 更新任务组
 */
export function UpdateTaskGroup(id: number, group: models$0.TaskGroup): $CancellablePromise<models$0.TaskGroup | null> {
    return $Call.ByID(15202956, id, group).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.TaskGroup.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TaskGroupDetailViewModel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
