// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TaskGroupService 任务组管理服务 - 负责任务组的增删改查和执行
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as executor$0 from "../executor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * CreateTaskGroup 创建新任务组
 */
export function CreateTaskGroup(group: config$0.TaskGroup): Promise<config$0.TaskGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3399746419, group) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * DeleteTaskGroup 删除任务组
 */
export function DeleteTaskGroup(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2162302226, id) as any;
    return $resultPromise;
}

/**
 * GetTaskGroup 根据 ID 获取单个任务组
 */
export function GetTaskGroup(id: string): Promise<config$0.TaskGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2623601141, id) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ListTaskGroups 获取所有任务组列表
 */
export function ListTaskGroups(): Promise<config$0.TaskGroup[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3904305468) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType2($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * ResolveSuspend 被前端调用（当用户在弹窗中选择动作后）
 */
export function ResolveSuspend(ip: string, action: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4170877605, ip, action) as any;
    return $resultPromise;
}

/**
 * ServiceStartup Wails 服务启动生命周期钩子
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3489890465, options) as any;
    return $resultPromise;
}

/**
 * StartTaskGroup 启动任务组执行
 */
export function StartTaskGroup(id: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3072082837, id) as any;
    return $resultPromise;
}

/**
 * UpdateTaskGroup 更新任务组
 */
export function UpdateTaskGroup(id: string, group: config$0.TaskGroup): Promise<config$0.TaskGroup | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(15202956, id, group) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * WailsSuspendHandler 构建代理 Suspend 钩子替换原先的控制台询问方式
 */
export function WailsSuspendHandler(): Promise<executor$0.SuspendHandler> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3833799237) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = config$0.TaskGroup.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
