// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TopologyService 拓扑服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as parser$0 from "../parser/models.js";

/**
 * BuildTopology 构建拓扑图
 */
export function BuildTopology(taskID: string): $CancellablePromise<models$0.TopologyBuildResult | null> {
    return $Call.ByID(878843081, taskID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDeviceTopologyDetail 获取设备的拓扑详情
 */
export function GetDeviceTopologyDetail(taskID: string, deviceIP: string): $CancellablePromise<parser$0.ParsedResult | null> {
    return $Call.ByID(3496034270, taskID, deviceIP).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetEdgeDetail 获取边详情
 */
export function GetEdgeDetail(taskID: string, edgeID: string): $CancellablePromise<models$0.TopologyEdgeDetailView | null> {
    return $Call.ByID(687663028, taskID, edgeID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetParseErrors 获取任务解析错误列表
 */
export function GetParseErrors(taskID: string): $CancellablePromise<parser$0.ParseErrorDetail[]> {
    return $Call.ByID(2589824020, taskID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetTopologyGraph 获取拓扑图视图
 */
export function GetTopologyGraph(taskID: string): $CancellablePromise<models$0.TopologyGraphView | null> {
    return $Call.ByID(1599731831, taskID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListTopologyEdges 列出拓扑边
 */
export function ListTopologyEdges(taskID: string): $CancellablePromise<models$0.TopologyEdge[]> {
    return $Call.ByID(2920768769, taskID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListTopologyNodes 列出拓扑节点
 */
export function ListTopologyNodes(taskID: string): $CancellablePromise<models$0.GraphNode[]> {
    return $Call.ByID(1283202942, taskID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ParseDiscoveryTask 解析发现任务的原始输出
 * 增强版：返回解析错误列表，供前端展示
 */
export function ParseDiscoveryTask(taskID: string): $CancellablePromise<parser$0.ParseErrorDetail[]> {
    return $Call.ByID(3480920266, taskID).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.TopologyBuildResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = parser$0.ParsedResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.TopologyEdgeDetailView.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = parser$0.ParseErrorDetail.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = models$0.TopologyGraphView.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = models$0.TopologyEdge.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = models$0.GraphNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
