// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CommandGroup 命令组
 */
export class CommandGroup {
    "id": number;
    "name": string;
    "description": string;

    /**
     * 命令列表
     */
    "commands": string[];

    /**
     * 标签列表
     */
    "tags": string[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new CommandGroup instance. */
    constructor($$source: Partial<CommandGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandGroup {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new CommandGroup($$parsedSource as Partial<CommandGroup>);
    }
}

/**
 * CompareResult 比对结果
 */
export class CompareResult {
    "reportId": string;
    "totalPlanned": number;
    "totalActual": number;
    "matched": number;
    "missingLinks": DiffItem[];
    "unexpectedLinks": DiffItem[];
    "inconsistentItems": DiffItem[];

    /** Creates a new CompareResult instance. */
    constructor($$source: Partial<CompareResult> = {}) {
        if (!("reportId" in $$source)) {
            this["reportId"] = "";
        }
        if (!("totalPlanned" in $$source)) {
            this["totalPlanned"] = 0;
        }
        if (!("totalActual" in $$source)) {
            this["totalActual"] = 0;
        }
        if (!("matched" in $$source)) {
            this["matched"] = 0;
        }
        if (!("missingLinks" in $$source)) {
            this["missingLinks"] = [];
        }
        if (!("unexpectedLinks" in $$source)) {
            this["unexpectedLinks"] = [];
        }
        if (!("inconsistentItems" in $$source)) {
            this["inconsistentItems"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompareResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompareResult {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("missingLinks" in $$parsedSource) {
            $$parsedSource["missingLinks"] = $$createField4_0($$parsedSource["missingLinks"]);
        }
        if ("unexpectedLinks" in $$parsedSource) {
            $$parsedSource["unexpectedLinks"] = $$createField5_0($$parsedSource["unexpectedLinks"]);
        }
        if ("inconsistentItems" in $$parsedSource) {
            $$parsedSource["inconsistentItems"] = $$createField6_0($$parsedSource["inconsistentItems"]);
        }
        return new CompareResult($$parsedSource as Partial<CompareResult>);
    }
}

/**
 * DeviceAsset 设备资产表
 */
export class DeviceAsset {
    "id": number;
    "ip": string;
    "port": number;
    "username": string;
    "protocol": string;

    /**
     * 映射到数据库的 group_name 列
     */
    "group": string;
    "displayName": string;
    "vendor": string;
    "role": string;
    "site": string;
    "description": string;

    /**
     * 标签列表
     */
    "tags": string[];
    "lastSeen": time$0.Time;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new DeviceAsset instance. */
    constructor($$source: Partial<DeviceAsset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceAsset {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new DeviceAsset($$parsedSource as Partial<DeviceAsset>);
    }
}

/**
 * DeviceAssetResponse 设备响应结构（包含密码，用于编辑场景）
 */
export class DeviceAssetResponse {
    "id": number;
    "ip": string;
    "port": number;
    "username": string;
    "protocol": string;

    /**
     * 映射到数据库的 group_name 列
     */
    "group": string;
    "displayName": string;
    "vendor": string;
    "role": string;
    "site": string;
    "description": string;

    /**
     * 标签列表
     */
    "tags": string[];
    "lastSeen": time$0.Time;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "password"?: string;

    /** Creates a new DeviceAssetResponse instance. */
    constructor($$source: Partial<DeviceAssetResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAssetResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceAssetResponse {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new DeviceAssetResponse($$parsedSource as Partial<DeviceAssetResponse>);
    }
}

/**
 * DiffItem 差异项
 */
export class DiffItem {
    "id": number;
    "reportId": string;

    /**
     * missing_link / unexpected_link / interface_mismatch / ...
     */
    "diffType": string;
    "aDeviceName": string;
    "aMgmtIp": string;
    "aIf": string;
    "bDeviceName": string;
    "bMgmtIp": string;
    "bIf": string;
    "expectedIf": string;
    "actualIf": string;
    "reason": string;
    "evidence": string[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new DiffItem instance. */
    constructor($$source: Partial<DiffItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("reportId" in $$source)) {
            this["reportId"] = "";
        }
        if (!("diffType" in $$source)) {
            this["diffType"] = "";
        }
        if (!("aDeviceName" in $$source)) {
            this["aDeviceName"] = "";
        }
        if (!("aMgmtIp" in $$source)) {
            this["aMgmtIp"] = "";
        }
        if (!("aIf" in $$source)) {
            this["aIf"] = "";
        }
        if (!("bDeviceName" in $$source)) {
            this["bDeviceName"] = "";
        }
        if (!("bMgmtIp" in $$source)) {
            this["bMgmtIp"] = "";
        }
        if (!("bIf" in $$source)) {
            this["bIf"] = "";
        }
        if (!("expectedIf" in $$source)) {
            this["expectedIf"] = "";
        }
        if (!("actualIf" in $$source)) {
            this["actualIf"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffItem {
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField12_0($$parsedSource["evidence"]);
        }
        return new DiffItem($$parsedSource as Partial<DiffItem>);
    }
}

/**
 * DiffReportView 差异报告视图
 */
export class DiffReportView {
    "id": string;
    "taskId": string;
    "planFileId": string;
    "planFileName": string;
    "totalPlanned": number;
    "totalActual": number;
    "matched": number;
    "missingLinks": number;
    "unexpectedLinks": number;
    "inconsistentItems": number;
    "createdAt": time$0.Time;

    /** Creates a new DiffReportView instance. */
    constructor($$source: Partial<DiffReportView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("planFileId" in $$source)) {
            this["planFileId"] = "";
        }
        if (!("planFileName" in $$source)) {
            this["planFileName"] = "";
        }
        if (!("totalPlanned" in $$source)) {
            this["totalPlanned"] = 0;
        }
        if (!("totalActual" in $$source)) {
            this["totalActual"] = 0;
        }
        if (!("matched" in $$source)) {
            this["matched"] = 0;
        }
        if (!("missingLinks" in $$source)) {
            this["missingLinks"] = 0;
        }
        if (!("unexpectedLinks" in $$source)) {
            this["unexpectedLinks"] = 0;
        }
        if (!("inconsistentItems" in $$source)) {
            this["inconsistentItems"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffReportView instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffReportView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffReportView($$parsedSource as Partial<DiffReportView>);
    }
}

/**
 * DiscoveryDeviceView 发现设备视图
 */
export class DiscoveryDeviceView {
    "id": number;
    "taskId": string;
    "deviceIp": string;
    "status": string;
    "errorMessage": string;
    "startedAt": time$0.Time | null;
    "finishedAt": time$0.Time | null;
    "displayName": string;
    "role": string;
    "site": string;
    "vendor": string;
    "model": string;
    "serialNumber": string;
    "version": string;
    "hostname": string;
    "mgmtIp": string;
    "chassisId": string;

    /** Creates a new DiscoveryDeviceView instance. */
    constructor($$source: Partial<DiscoveryDeviceView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("deviceIp" in $$source)) {
            this["deviceIp"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("mgmtIp" in $$source)) {
            this["mgmtIp"] = "";
        }
        if (!("chassisId" in $$source)) {
            this["chassisId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryDeviceView instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryDeviceView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveryDeviceView($$parsedSource as Partial<DiscoveryDeviceView>);
    }
}

/**
 * DiscoveryTaskView 发现任务视图
 */
export class DiscoveryTaskView {
    "id": string;
    "name": string;
    "status": string;
    "totalCount": number;
    "successCount": number;
    "failedCount": number;
    "startedAt": time$0.Time | null;
    "finishedAt": time$0.Time | null;
    "createdAt": time$0.Time;
    "maxWorkers": number;
    "vendor": string;

    /** Creates a new DiscoveryTaskView instance. */
    constructor($$source: Partial<DiscoveryTaskView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryTaskView instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryTaskView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveryTaskView($$parsedSource as Partial<DiscoveryTaskView>);
    }
}

/**
 * EdgeEvidence 边证据
 */
export class EdgeEvidence {
    /**
     * 证据类型: lldp / fdb / arp / aggregate / identity
     */
    "type": string;

    /**
     * 证据来源设备
     */
    "deviceId": string;

    /**
     * 来源命令 key
     */
    "command": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /**
     * 证据摘要
     */
    "summary": string;

    /**
     * 兼容字段: 来源
     */
    "source": string;

    /**
     * 本地接口
     */
    "localIf": string;

    /**
     * 远端名称
     */
    "remoteName": string;

    /**
     * 远端接口
     */
    "remoteIf": string;

    /**
     * 远端MAC
     */
    "remoteMac": string;

    /**
     * 远端IP
     */
    "remoteIp": string;

    /**
     * 时间戳
     */
    "timestamp"?: string;

    /** Creates a new EdgeEvidence instance. */
    constructor($$source: Partial<EdgeEvidence> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("localIf" in $$source)) {
            this["localIf"] = "";
        }
        if (!("remoteName" in $$source)) {
            this["remoteName"] = "";
        }
        if (!("remoteIf" in $$source)) {
            this["remoteIf"] = "";
        }
        if (!("remoteMac" in $$source)) {
            this["remoteMac"] = "";
        }
        if (!("remoteIp" in $$source)) {
            this["remoteIp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EdgeEvidence instance from a string or object.
     */
    static createFrom($$source: any = {}): EdgeEvidence {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EdgeEvidence($$parsedSource as Partial<EdgeEvidence>);
    }
}

/**
 * ExecutionDeviceRecord 设备执行记录（嵌套在 ExecutionRecord 中）
 */
export class ExecutionDeviceRecord {
    "ip": string;
    "status": string;
    "totalCmd": number;
    "execCmd": number;
    "errorMsg": string;
    "logCount": number;
    "logTail": string[];
    "logFilePath": string;
    "summaryLogPath": string;
    "detailLogPath": string;
    "rawLogPath": string;

    /** Creates a new ExecutionDeviceRecord instance. */
    constructor($$source: Partial<ExecutionDeviceRecord> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("totalCmd" in $$source)) {
            this["totalCmd"] = 0;
        }
        if (!("execCmd" in $$source)) {
            this["execCmd"] = 0;
        }
        if (!("errorMsg" in $$source)) {
            this["errorMsg"] = "";
        }
        if (!("logCount" in $$source)) {
            this["logCount"] = 0;
        }
        if (!("logTail" in $$source)) {
            this["logTail"] = [];
        }
        if (!("logFilePath" in $$source)) {
            this["logFilePath"] = "";
        }
        if (!("summaryLogPath" in $$source)) {
            this["summaryLogPath"] = "";
        }
        if (!("detailLogPath" in $$source)) {
            this["detailLogPath"] = "";
        }
        if (!("rawLogPath" in $$source)) {
            this["rawLogPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionDeviceRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionDeviceRecord {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logTail" in $$parsedSource) {
            $$parsedSource["logTail"] = $$createField6_0($$parsedSource["logTail"]);
        }
        return new ExecutionDeviceRecord($$parsedSource as Partial<ExecutionDeviceRecord>);
    }
}

/**
 * ExecutionRecord 历史执行记录表
 */
export class ExecutionRecord {
    "id": string;

    /**
     * task_group / engine_service / backup_service / discovery_service
     */
    "runnerSource": string;

    /**
     * 运行实例ID，可为空
     */
    "runnerId": string;

    /**
     * 任务组ID，非任务组执行时为空
     */
    "taskGroupId": string;

    /**
     * 任务组名称快照
     */
    "taskGroupName": string;

    /**
     * 执行任务名称快照
     */
    "taskName": string;

    /**
     * group / binding / manual / backup / discovery
     */
    "mode": string;

    /**
     * completed / partial / failed / cancelled
     */
    "status": string;
    "totalDevices": number;
    "finishedCount": number;
    "successCount": number;
    "errorCount": number;
    "abortedCount": number;
    "warningCount": number;
    "startedAt": string;
    "finishedAt": string;
    "durationMs": number;
    "reportPath": string;
    "devices": ExecutionDeviceRecord[];
    "createdAt": string;

    /** Creates a new ExecutionRecord instance. */
    constructor($$source: Partial<ExecutionRecord> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("runnerSource" in $$source)) {
            this["runnerSource"] = "";
        }
        if (!("runnerId" in $$source)) {
            this["runnerId"] = "";
        }
        if (!("taskGroupId" in $$source)) {
            this["taskGroupId"] = "";
        }
        if (!("taskGroupName" in $$source)) {
            this["taskGroupName"] = "";
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("totalDevices" in $$source)) {
            this["totalDevices"] = 0;
        }
        if (!("finishedCount" in $$source)) {
            this["finishedCount"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("errorCount" in $$source)) {
            this["errorCount"] = 0;
        }
        if (!("abortedCount" in $$source)) {
            this["abortedCount"] = 0;
        }
        if (!("warningCount" in $$source)) {
            this["warningCount"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("reportPath" in $$source)) {
            this["reportPath"] = "";
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionRecord {
        const $$createField18_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField18_0($$parsedSource["devices"]);
        }
        return new ExecutionRecord($$parsedSource as Partial<ExecutionRecord>);
    }
}

/**
 * GlobalSettings 全局运行参数
 */
export class GlobalSettings {
    "id": number;

    /**
     * 并发数 (当前硬编码为 32)
     */
    "maxWorkers": number;

    /**
     * SSH/SFTP 连接超时 (如 "10s")
     */
    "connectTimeout": string;

    /**
     * 单条命令默认超时 (如 "30s")
     */
    "commandTimeout": string;

    /**
     * 统一数据根目录
     */
    "storageRoot": string;

    /**
     * "pause" | "skip" | "abort"
     */
    "errorMode": string;

    /**
     * 调试日志开关
     * 启用 DEBUG 级别日志
     */
    "debug": boolean;

    /**
     * 启用 VERBOSE 级别日志（包含详细调试信息）
     */
    "verbose": boolean;

    /**
     * SSH算法配置
     */
    "sshAlgorithms": SSHAlgorithmSettings;

    /**
     * SSH主机密钥校验策略: strict / accept_new / insecure
     */
    "sshHostKeyPolicy": string;

    /**
     * known_hosts 文件路径（为空时使用默认路径）
     */
    "sshKnownHostsPath": string;

    /** Creates a new GlobalSettings instance. */
    constructor($$source: Partial<GlobalSettings> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("connectTimeout" in $$source)) {
            this["connectTimeout"] = "";
        }
        if (!("commandTimeout" in $$source)) {
            this["commandTimeout"] = "";
        }
        if (!("storageRoot" in $$source)) {
            this["storageRoot"] = "";
        }
        if (!("errorMode" in $$source)) {
            this["errorMode"] = "";
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("verbose" in $$source)) {
            this["verbose"] = false;
        }
        if (!("sshAlgorithms" in $$source)) {
            this["sshAlgorithms"] = (new SSHAlgorithmSettings());
        }
        if (!("sshHostKeyPolicy" in $$source)) {
            this["sshHostKeyPolicy"] = "";
        }
        if (!("sshKnownHostsPath" in $$source)) {
            this["sshKnownHostsPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalSettings {
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sshAlgorithms" in $$parsedSource) {
            $$parsedSource["sshAlgorithms"] = $$createField8_0($$parsedSource["sshAlgorithms"]);
        }
        return new GlobalSettings($$parsedSource as Partial<GlobalSettings>);
    }
}

/**
 * GraphEdge 图边
 */
export class GraphEdge {
    "id": string;
    "source": string;
    "target": string;
    "sourceIf": string;
    "targetIf": string;
    "logicalSourceIf": string;
    "logicalTargetIf": string;
    "edgeType": string;
    "status": string;
    "confidence": number;

    /** Creates a new GraphEdge instance. */
    constructor($$source: Partial<GraphEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("sourceIf" in $$source)) {
            this["sourceIf"] = "";
        }
        if (!("targetIf" in $$source)) {
            this["targetIf"] = "";
        }
        if (!("logicalSourceIf" in $$source)) {
            this["logicalSourceIf"] = "";
        }
        if (!("logicalTargetIf" in $$source)) {
            this["logicalTargetIf"] = "";
        }
        if (!("edgeType" in $$source)) {
            this["edgeType"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphEdge($$parsedSource as Partial<GraphEdge>);
    }
}

/**
 * GraphNode 图节点
 */
export class GraphNode {
    "id": string;
    "label": string;
    "ip": string;
    "vendor": string;
    "model": string;
    "role": string;
    "site": string;
    "serialNumber": string;

    /** Creates a new GraphNode instance. */
    constructor($$source: Partial<GraphNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode($$parsedSource as Partial<GraphNode>);
    }
}

/**
 * PlanImportResult 规划导入结果
 */
export class PlanImportResult {
    "planFileId": string;
    "totalLinks": number;
    "warnings"?: string[];

    /** Creates a new PlanImportResult instance. */
    constructor($$source: Partial<PlanImportResult> = {}) {
        if (!("planFileId" in $$source)) {
            this["planFileId"] = "";
        }
        if (!("totalLinks" in $$source)) {
            this["totalLinks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanImportResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new PlanImportResult($$parsedSource as Partial<PlanImportResult>);
    }
}

/**
 * PlanUploadView 规划文件视图
 */
export class PlanUploadView {
    "id": string;
    "fileName": string;
    "filePath": string;
    "totalLinks": number;
    "warnings"?: string[];
    "importedAt": time$0.Time;

    /** Creates a new PlanUploadView instance. */
    constructor($$source: Partial<PlanUploadView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("totalLinks" in $$source)) {
            this["totalLinks"] = 0;
        }
        if (!("importedAt" in $$source)) {
            this["importedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlanUploadView instance from a string or object.
     */
    static createFrom($$source: any = {}): PlanUploadView {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField4_0($$parsedSource["warnings"]);
        }
        return new PlanUploadView($$parsedSource as Partial<PlanUploadView>);
    }
}

/**
 * SSHAlgorithmSettings SSH算法配置
 */
export class SSHAlgorithmSettings {
    /**
     * 加密算法 (Ciphers)
     */
    "ciphers": string[];

    /**
     * 密钥交换算法
     */
    "keyExchanges": string[];

    /**
     * 消息认证码
     */
    "macs": string[];

    /**
     * 主机密钥算法
     */
    "hostKeyAlgorithms": string[];

    /**
     * 预设模式: "secure" | "compatible" | "custom"
     */
    "presetMode": string;

    /** Creates a new SSHAlgorithmSettings instance. */
    constructor($$source: Partial<SSHAlgorithmSettings> = {}) {
        if (!("ciphers" in $$source)) {
            this["ciphers"] = [];
        }
        if (!("keyExchanges" in $$source)) {
            this["keyExchanges"] = [];
        }
        if (!("macs" in $$source)) {
            this["macs"] = [];
        }
        if (!("hostKeyAlgorithms" in $$source)) {
            this["hostKeyAlgorithms"] = [];
        }
        if (!("presetMode" in $$source)) {
            this["presetMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAlgorithmSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAlgorithmSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField0_0($$parsedSource["ciphers"]);
        }
        if ("keyExchanges" in $$parsedSource) {
            $$parsedSource["keyExchanges"] = $$createField1_0($$parsedSource["keyExchanges"]);
        }
        if ("macs" in $$parsedSource) {
            $$parsedSource["macs"] = $$createField2_0($$parsedSource["macs"]);
        }
        if ("hostKeyAlgorithms" in $$parsedSource) {
            $$parsedSource["hostKeyAlgorithms"] = $$createField3_0($$parsedSource["hostKeyAlgorithms"]);
        }
        return new SSHAlgorithmSettings($$parsedSource as Partial<SSHAlgorithmSettings>);
    }
}

/**
 * StartDiscoveryRequest 启动发现任务请求
 */
export class StartDiscoveryRequest {
    "deviceIds": string[];
    "groupNames": string[];
    "vendor": string;
    "maxWorkers": number;
    "timeoutSec": number;

    /** Creates a new StartDiscoveryRequest instance. */
    constructor($$source: Partial<StartDiscoveryRequest> = {}) {
        if (!("deviceIds" in $$source)) {
            this["deviceIds"] = [];
        }
        if (!("groupNames" in $$source)) {
            this["groupNames"] = [];
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartDiscoveryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartDiscoveryRequest {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deviceIds" in $$parsedSource) {
            $$parsedSource["deviceIds"] = $$createField0_0($$parsedSource["deviceIds"]);
        }
        if ("groupNames" in $$parsedSource) {
            $$parsedSource["groupNames"] = $$createField1_0($$parsedSource["groupNames"]);
        }
        return new StartDiscoveryRequest($$parsedSource as Partial<StartDiscoveryRequest>);
    }
}

/**
 * TaskGroup 任务组
 */
export class TaskGroup {
    "id": number;
    "name": string;
    "description": string;
    "deviceGroup": string;
    "commandGroup": string;
    "maxWorkers": number;
    "timeout": number;

    /**
     * "group" 模式A | "binding" 模式B
     */
    "mode": string;

    /**
     * 任务项列表
     */
    "items": TaskItem[];

    /**
     * "pending" | "running" | "completed" | "failed"
     */
    "status": string;
    "tags": string[];
    "enableRawLog": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new TaskGroup instance. */
    constructor($$source: Partial<TaskGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("deviceGroup" in $$source)) {
            this["deviceGroup"] = "";
        }
        if (!("commandGroup" in $$source)) {
            this["commandGroup"] = "";
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("enableRawLog" in $$source)) {
            this["enableRawLog"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskGroup {
        const $$createField8_0 = $$createType7;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField8_0($$parsedSource["items"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new TaskGroup($$parsedSource as Partial<TaskGroup>);
    }
}

/**
 * TaskItem 单个任务项（一组命令绑定一组设备）
 */
export class TaskItem {
    /**
     * 命令组ID（模式A使用）
     */
    "commandGroupId": string;

    /**
     * 直接命令列表（模式B使用）
     */
    "commands": string[];

    /**
     * 绑定的设备ID列表
     */
    "deviceIDs": number[];

    /** Creates a new TaskItem instance. */
    constructor($$source: Partial<TaskItem> = {}) {
        if (!("commandGroupId" in $$source)) {
            this["commandGroupId"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("deviceIDs" in $$source)) {
            this["deviceIDs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskItem {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField1_0($$parsedSource["commands"]);
        }
        if ("deviceIDs" in $$parsedSource) {
            $$parsedSource["deviceIDs"] = $$createField2_0($$parsedSource["deviceIDs"]);
        }
        return new TaskItem($$parsedSource as Partial<TaskItem>);
    }
}

/**
 * TaskStartResponse 任务启动响应
 */
export class TaskStartResponse {
    "taskId": string;

    /** Creates a new TaskStartResponse instance. */
    constructor($$source: Partial<TaskStartResponse> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskStartResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskStartResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskStartResponse($$parsedSource as Partial<TaskStartResponse>);
    }
}

/**
 * TopologyBuildResult 拓扑构建结果
 */
export class TopologyBuildResult {
    "taskId": string;
    "totalEdges": number;
    "confirmedEdges": number;
    "semiConfirmedEdges": number;
    "inferredEdges": number;
    "conflictEdges": number;
    "buildTime": time$0.Duration;
    "errors"?: string[];

    /** Creates a new TopologyBuildResult instance. */
    constructor($$source: Partial<TopologyBuildResult> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("totalEdges" in $$source)) {
            this["totalEdges"] = 0;
        }
        if (!("confirmedEdges" in $$source)) {
            this["confirmedEdges"] = 0;
        }
        if (!("semiConfirmedEdges" in $$source)) {
            this["semiConfirmedEdges"] = 0;
        }
        if (!("inferredEdges" in $$source)) {
            this["inferredEdges"] = 0;
        }
        if (!("conflictEdges" in $$source)) {
            this["conflictEdges"] = 0;
        }
        if (!("buildTime" in $$source)) {
            this["buildTime"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopologyBuildResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TopologyBuildResult {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField7_0($$parsedSource["errors"]);
        }
        return new TopologyBuildResult($$parsedSource as Partial<TopologyBuildResult>);
    }
}

/**
 * TopologyEdge 拓扑边（链路）
 */
export class TopologyEdge {
    "id": string;
    "taskId": string;
    "aDeviceId": string;
    "aIf": string;
    "bDeviceId": string;
    "bIf": string;
    "logicalAIf": string;
    "logicalBIf": string;

    /**
     * physical / logical_aggregate
     */
    "edgeType": string;

    /**
     * confirmed / semi_confirmed / inferred / conflict
     */
    "status": string;
    "confidence": number;
    "discoveryMethods": string[];
    "evidence": EdgeEvidence[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new TopologyEdge instance. */
    constructor($$source: Partial<TopologyEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("aDeviceId" in $$source)) {
            this["aDeviceId"] = "";
        }
        if (!("aIf" in $$source)) {
            this["aIf"] = "";
        }
        if (!("bDeviceId" in $$source)) {
            this["bDeviceId"] = "";
        }
        if (!("bIf" in $$source)) {
            this["bIf"] = "";
        }
        if (!("logicalAIf" in $$source)) {
            this["logicalAIf"] = "";
        }
        if (!("logicalBIf" in $$source)) {
            this["logicalBIf"] = "";
        }
        if (!("edgeType" in $$source)) {
            this["edgeType"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("discoveryMethods" in $$source)) {
            this["discoveryMethods"] = [];
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopologyEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): TopologyEdge {
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("discoveryMethods" in $$parsedSource) {
            $$parsedSource["discoveryMethods"] = $$createField11_0($$parsedSource["discoveryMethods"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField12_0($$parsedSource["evidence"]);
        }
        return new TopologyEdge($$parsedSource as Partial<TopologyEdge>);
    }
}

/**
 * TopologyEdgeDetailView 边详情视图
 */
export class TopologyEdgeDetailView {
    "id": string;
    "aDevice": GraphNode;
    "aIf": string;
    "logicalAIf": string;
    "bDevice": GraphNode;
    "bIf": string;
    "logicalBIf": string;
    "edgeType": string;
    "status": string;
    "confidence": number;
    "discoveryMethods": string[];
    "evidence": EdgeEvidence[];

    /** Creates a new TopologyEdgeDetailView instance. */
    constructor($$source: Partial<TopologyEdgeDetailView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("aDevice" in $$source)) {
            this["aDevice"] = (new GraphNode());
        }
        if (!("aIf" in $$source)) {
            this["aIf"] = "";
        }
        if (!("logicalAIf" in $$source)) {
            this["logicalAIf"] = "";
        }
        if (!("bDevice" in $$source)) {
            this["bDevice"] = (new GraphNode());
        }
        if (!("bIf" in $$source)) {
            this["bIf"] = "";
        }
        if (!("logicalBIf" in $$source)) {
            this["logicalBIf"] = "";
        }
        if (!("edgeType" in $$source)) {
            this["edgeType"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("discoveryMethods" in $$source)) {
            this["discoveryMethods"] = [];
        }
        if (!("evidence" in $$source)) {
            this["evidence"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopologyEdgeDetailView instance from a string or object.
     */
    static createFrom($$source: any = {}): TopologyEdgeDetailView {
        const $$createField1_0 = $$createType11;
        const $$createField4_0 = $$createType11;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aDevice" in $$parsedSource) {
            $$parsedSource["aDevice"] = $$createField1_0($$parsedSource["aDevice"]);
        }
        if ("bDevice" in $$parsedSource) {
            $$parsedSource["bDevice"] = $$createField4_0($$parsedSource["bDevice"]);
        }
        if ("discoveryMethods" in $$parsedSource) {
            $$parsedSource["discoveryMethods"] = $$createField10_0($$parsedSource["discoveryMethods"]);
        }
        if ("evidence" in $$parsedSource) {
            $$parsedSource["evidence"] = $$createField11_0($$parsedSource["evidence"]);
        }
        return new TopologyEdgeDetailView($$parsedSource as Partial<TopologyEdgeDetailView>);
    }
}

/**
 * TopologyGraphView 拓扑图视图
 */
export class TopologyGraphView {
    "taskId": string;
    "nodes": GraphNode[];
    "edges": GraphEdge[];

    /** Creates a new TopologyGraphView instance. */
    constructor($$source: Partial<TopologyGraphView> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopologyGraphView instance from a string or object.
     */
    static createFrom($$source: any = {}): TopologyGraphView {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField1_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField2_0($$parsedSource["edges"]);
        }
        return new TopologyGraphView($$parsedSource as Partial<TopologyGraphView>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DiffItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ExecutionDeviceRecord.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SSHAlgorithmSettings.createFrom;
const $$createType6 = TaskItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = EdgeEvidence.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = GraphNode.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = GraphEdge.createFrom;
const $$createType14 = $Create.Array($$createType13);
