// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CommandGroup 命令组
 */
export class CommandGroup {
    "id": number;
    "name": string;
    "description": string;

    /**
     * 命令列表
     */
    "commands": string[];

    /**
     * 标签列表
     */
    "tags": string[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new CommandGroup instance. */
    constructor($$source: Partial<CommandGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandGroup {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField3_0($$parsedSource["commands"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new CommandGroup($$parsedSource as Partial<CommandGroup>);
    }
}

/**
 * DeviceAsset 设备资产表
 */
export class DeviceAsset {
    "id": number;
    "ip": string;
    "port": number;
    "username": string;
    "password": string;
    "protocol": string;

    /**
     * 映射到数据库的 group_name 列
     */
    "group": string;
    "displayName": string;
    "vendor": string;
    "role": string;
    "site": string;
    "description": string;

    /**
     * 标签列表
     */
    "tags": string[];
    "lastSeen": time$0.Time;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new DeviceAsset instance. */
    constructor($$source: Partial<DeviceAsset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceAsset {
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField12_0($$parsedSource["tags"]);
        }
        return new DeviceAsset($$parsedSource as Partial<DeviceAsset>);
    }
}

/**
 * DiscoveryDeviceView 发现设备视图
 */
export class DiscoveryDeviceView {
    "id": number;
    "taskId": string;
    "deviceIp": string;
    "status": string;
    "errorMessage": string;
    "startedAt": time$0.Time | null;
    "finishedAt": time$0.Time | null;
    "vendor": string;
    "model": string;
    "serialNumber": string;
    "version": string;

    /** Creates a new DiscoveryDeviceView instance. */
    constructor($$source: Partial<DiscoveryDeviceView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("deviceIp" in $$source)) {
            this["deviceIp"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryDeviceView instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryDeviceView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveryDeviceView($$parsedSource as Partial<DiscoveryDeviceView>);
    }
}

/**
 * DiscoveryTaskView 发现任务视图
 */
export class DiscoveryTaskView {
    "id": string;
    "name": string;
    "status": string;
    "totalCount": number;
    "successCount": number;
    "failedCount": number;
    "startedAt": time$0.Time | null;
    "finishedAt": time$0.Time | null;
    "createdAt": time$0.Time;
    "maxWorkers": number;
    "vendor": string;

    /** Creates a new DiscoveryTaskView instance. */
    constructor($$source: Partial<DiscoveryTaskView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            this["failedCount"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            this["finishedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryTaskView instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryTaskView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveryTaskView($$parsedSource as Partial<DiscoveryTaskView>);
    }
}

/**
 * GlobalSettings 全局运行参数
 */
export class GlobalSettings {
    "id": number;

    /**
     * 并发数 (当前硬编码为 32)
     */
    "maxWorkers": number;

    /**
     * SSH/SFTP 连接超时 (如 "10s")
     */
    "connectTimeout": string;

    /**
     * 单条命令默认超时 (如 "30s")
     */
    "commandTimeout": string;

    /**
     * 统一数据根目录
     */
    "storageRoot": string;

    /**
     * "pause" | "skip" | "abort"
     */
    "errorMode": string;

    /**
     * 调试日志开关
     * 启用 DEBUG 级别日志
     */
    "debug": boolean;

    /**
     * 启用 VERBOSE 级别日志（包含详细调试信息）
     */
    "verbose": boolean;

    /**
     * SSH算法配置
     */
    "sshAlgorithms": SSHAlgorithmSettings;

    /** Creates a new GlobalSettings instance. */
    constructor($$source: Partial<GlobalSettings> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("connectTimeout" in $$source)) {
            this["connectTimeout"] = "";
        }
        if (!("commandTimeout" in $$source)) {
            this["commandTimeout"] = "";
        }
        if (!("storageRoot" in $$source)) {
            this["storageRoot"] = "";
        }
        if (!("errorMode" in $$source)) {
            this["errorMode"] = "";
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("verbose" in $$source)) {
            this["verbose"] = false;
        }
        if (!("sshAlgorithms" in $$source)) {
            this["sshAlgorithms"] = (new SSHAlgorithmSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobalSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobalSettings {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sshAlgorithms" in $$parsedSource) {
            $$parsedSource["sshAlgorithms"] = $$createField8_0($$parsedSource["sshAlgorithms"]);
        }
        return new GlobalSettings($$parsedSource as Partial<GlobalSettings>);
    }
}

/**
 * SSHAlgorithmSettings SSH算法配置
 */
export class SSHAlgorithmSettings {
    /**
     * 加密算法 (Ciphers)
     */
    "ciphers": string[];

    /**
     * 密钥交换算法
     */
    "keyExchanges": string[];

    /**
     * 消息认证码
     */
    "macs": string[];

    /**
     * 主机密钥算法
     */
    "hostKeyAlgorithms": string[];

    /**
     * 预设模式: "secure" | "compatible" | "custom"
     */
    "presetMode": string;

    /** Creates a new SSHAlgorithmSettings instance. */
    constructor($$source: Partial<SSHAlgorithmSettings> = {}) {
        if (!("ciphers" in $$source)) {
            this["ciphers"] = [];
        }
        if (!("keyExchanges" in $$source)) {
            this["keyExchanges"] = [];
        }
        if (!("macs" in $$source)) {
            this["macs"] = [];
        }
        if (!("hostKeyAlgorithms" in $$source)) {
            this["hostKeyAlgorithms"] = [];
        }
        if (!("presetMode" in $$source)) {
            this["presetMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHAlgorithmSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHAlgorithmSettings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ciphers" in $$parsedSource) {
            $$parsedSource["ciphers"] = $$createField0_0($$parsedSource["ciphers"]);
        }
        if ("keyExchanges" in $$parsedSource) {
            $$parsedSource["keyExchanges"] = $$createField1_0($$parsedSource["keyExchanges"]);
        }
        if ("macs" in $$parsedSource) {
            $$parsedSource["macs"] = $$createField2_0($$parsedSource["macs"]);
        }
        if ("hostKeyAlgorithms" in $$parsedSource) {
            $$parsedSource["hostKeyAlgorithms"] = $$createField3_0($$parsedSource["hostKeyAlgorithms"]);
        }
        return new SSHAlgorithmSettings($$parsedSource as Partial<SSHAlgorithmSettings>);
    }
}

/**
 * StartDiscoveryRequest 启动发现任务请求
 */
export class StartDiscoveryRequest {
    "deviceIds": string[];
    "groupNames": string[];
    "vendor": string;
    "maxWorkers": number;
    "timeoutSec": number;

    /** Creates a new StartDiscoveryRequest instance. */
    constructor($$source: Partial<StartDiscoveryRequest> = {}) {
        if (!("deviceIds" in $$source)) {
            this["deviceIds"] = [];
        }
        if (!("groupNames" in $$source)) {
            this["groupNames"] = [];
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartDiscoveryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartDiscoveryRequest {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deviceIds" in $$parsedSource) {
            $$parsedSource["deviceIds"] = $$createField0_0($$parsedSource["deviceIds"]);
        }
        if ("groupNames" in $$parsedSource) {
            $$parsedSource["groupNames"] = $$createField1_0($$parsedSource["groupNames"]);
        }
        return new StartDiscoveryRequest($$parsedSource as Partial<StartDiscoveryRequest>);
    }
}

/**
 * TaskGroup 任务组
 */
export class TaskGroup {
    "id": number;
    "name": string;
    "description": string;
    "deviceGroup": string;
    "commandGroup": string;
    "maxWorkers": number;
    "timeout": number;

    /**
     * "group" 模式A | "binding" 模式B
     */
    "mode": string;

    /**
     * 任务项列表
     */
    "items": TaskItem[];

    /**
     * "pending" | "running" | "completed" | "failed"
     */
    "status": string;
    "tags": string[];
    "enableRawLog": boolean;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new TaskGroup instance. */
    constructor($$source: Partial<TaskGroup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("deviceGroup" in $$source)) {
            this["deviceGroup"] = "";
        }
        if (!("commandGroup" in $$source)) {
            this["commandGroup"] = "";
        }
        if (!("maxWorkers" in $$source)) {
            this["maxWorkers"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("enableRawLog" in $$source)) {
            this["enableRawLog"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskGroup {
        const $$createField8_0 = $$createType3;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField8_0($$parsedSource["items"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new TaskGroup($$parsedSource as Partial<TaskGroup>);
    }
}

/**
 * TaskItem 单个任务项（一组命令绑定一组设备）
 */
export class TaskItem {
    /**
     * 命令组ID（模式A使用）
     */
    "commandGroupId": string;

    /**
     * 直接命令列表（模式B使用）
     */
    "commands": string[];

    /**
     * 绑定的设备ID列表
     */
    "deviceIDs": number[];

    /** Creates a new TaskItem instance. */
    constructor($$source: Partial<TaskItem> = {}) {
        if (!("commandGroupId" in $$source)) {
            this["commandGroupId"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }
        if (!("deviceIDs" in $$source)) {
            this["deviceIDs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskItem {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField1_0($$parsedSource["commands"]);
        }
        if ("deviceIDs" in $$parsedSource) {
            $$parsedSource["deviceIDs"] = $$createField2_0($$parsedSource["deviceIDs"]);
        }
        return new TaskItem($$parsedSource as Partial<TaskItem>);
    }
}

/**
 * TaskStartResponse 任务启动响应
 */
export class TaskStartResponse {
    "taskId": string;

    /** Creates a new TaskStartResponse instance. */
    constructor($$source: Partial<TaskStartResponse> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskStartResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskStartResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskStartResponse($$parsedSource as Partial<TaskStartResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SSHAlgorithmSettings.createFrom;
const $$createType2 = TaskItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
