// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * DeviceViewState 单设备视图状态（用于前端快照）
 */
export class DeviceViewState {
    "ip": string;

    /**
     * running/success/error/aborted/waiting
     */
    "status": string;

    /**
     * 已截断的日志数组
     */
    "logs": string[];

    /**
     * 原始日志总条数
     */
    "logCount": number;

    /**
     * 是否已截断标记
     */
    "truncated": boolean;

    /**
     * 当前执行命令索引
     */
    "cmdIndex": number;

    /**
     * 总命令数
     */
    "totalCmd": number;

    /**
     * 当前状态消息
     */
    "message": string;

    /** Creates a new DeviceViewState instance. */
    constructor($$source: Partial<DeviceViewState> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }
        if (!("logCount" in $$source)) {
            this["logCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("cmdIndex" in $$source)) {
            this["cmdIndex"] = 0;
        }
        if (!("totalCmd" in $$source)) {
            this["totalCmd"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceViewState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceViewState {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField2_0($$parsedSource["logs"]);
        }
        return new DeviceViewState($$parsedSource as Partial<DeviceViewState>);
    }
}

/**
 * ExecutionSnapshot 执行快照（前端直接绑定渲染）
 */
export class ExecutionSnapshot {
    "taskName": string;
    "totalDevices": number;
    "finishedCount": number;

    /**
     * 0-100
     */
    "progress": number;
    "isRunning": boolean;
    "startTime": string;
    "devices": DeviceViewState[];

    /** Creates a new ExecutionSnapshot instance. */
    constructor($$source: Partial<ExecutionSnapshot> = {}) {
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("totalDevices" in $$source)) {
            this["totalDevices"] = 0;
        }
        if (!("finishedCount" in $$source)) {
            this["finishedCount"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("isRunning" in $$source)) {
            this["isRunning"] = false;
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionSnapshot {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField6_0($$parsedSource["devices"]);
        }
        return new ExecutionSnapshot($$parsedSource as Partial<ExecutionSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DeviceViewState.createFrom;
const $$createType2 = $Create.Array($$createType1);
