// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CommandSpec 命令规格定义
 */
export class CommandSpec {
    /**
     * 实际执行的命令
     */
    "command": string;

    /**
     * 唯一标识：version, lldp_neighbor, interface 等
     */
    "commandKey": string;

    /**
     * 超时秒数
     */
    "timeoutSec": number;

    /** Creates a new CommandSpec instance. */
    constructor($$source: Partial<CommandSpec> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandSpec instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandSpec {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandSpec($$parsedSource as Partial<CommandSpec>);
    }
}

export const DiscoveryDeviceView = models$0.DiscoveryDeviceView;
export type DiscoveryDeviceView = models$0.DiscoveryDeviceView;

export const DiscoveryTaskView = models$0.DiscoveryTaskView;
export type DiscoveryTaskView = models$0.DiscoveryTaskView;

export const StartDiscoveryRequest = models$0.StartDiscoveryRequest;
export type StartDiscoveryRequest = models$0.StartDiscoveryRequest;

export const TaskStartResponse = models$0.TaskStartResponse;
export type TaskStartResponse = models$0.TaskStartResponse;

/**
 * VendorCommandProfile 厂商命令配置
 */
export class VendorCommandProfile {
    /**
     * 厂商标识
     */
    "vendor": string;

    /**
     * 厂商名称
     */
    "name": string;

    /**
     * 命令列表
     */
    "commands": CommandSpec[];

    /** Creates a new VendorCommandProfile instance. */
    constructor($$source: Partial<VendorCommandProfile> = {}) {
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("commands" in $$source)) {
            this["commands"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VendorCommandProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): VendorCommandProfile {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commands" in $$parsedSource) {
            $$parsedSource["commands"] = $$createField2_0($$parsedSource["commands"]);
        }
        return new VendorCommandProfile($$parsedSource as Partial<VendorCommandProfile>);
    }
}

// Private type creation functions
const $$createType0 = CommandSpec.createFrom;
const $$createType1 = $Create.Array($$createType0);
