// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * BuildRequest 构建请求
 */
export class BuildRequest {
    /**
     * 模板文本
     */
    "template": string;

    /**
     * 变量列表
     */
    "variables": VarInput[];

    /** Creates a new BuildRequest instance. */
    constructor($$source: Partial<BuildRequest> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("variables" in $$source)) {
            this["variables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildRequest {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField1_0($$parsedSource["variables"]);
        }
        return new BuildRequest($$parsedSource as Partial<BuildRequest>);
    }
}

/**
 * BuildResult 构建结果
 */
export class BuildResult {
    /**
     * 生成的配置块
     */
    "blocks": string[];

    /**
     * 总数量
     */
    "total": number;

    /**
     * 警告信息
     */
    "warnings": string[];

    /** Creates a new BuildResult instance. */
    constructor($$source: Partial<BuildResult> = {}) {
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildResult {
        const $$createField0_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField0_0($$parsedSource["blocks"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new BuildResult($$parsedSource as Partial<BuildResult>);
    }
}

/**
 * ExpandRequest 语法糖展开请求
 */
export class ExpandRequest {
    /**
     * 值字符串
     */
    "valueString": string;

    /**
     * 目标最大长度（用于等差数列补全）
     */
    "maxLen": number;

    /** Creates a new ExpandRequest instance. */
    constructor($$source: Partial<ExpandRequest> = {}) {
        if (!("valueString" in $$source)) {
            this["valueString"] = "";
        }
        if (!("maxLen" in $$source)) {
            this["maxLen"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExpandRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExpandRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExpandRequest($$parsedSource as Partial<ExpandRequest>);
    }
}

/**
 * ExpandResult 语法糖展开结果
 */
export class ExpandResult {
    /**
     * 展开后的值数组
     */
    "values": string[];

    /**
     * 原始长度
     */
    "originalLen": number;

    /**
     * 展开后长度
     */
    "expandedLen": number;

    /**
     * 是否发生了展开
     */
    "hasExpanded": boolean;

    /**
     * 是否进行了等差推断补全
     */
    "hasInferred": boolean;

    /**
     * 警告信息
     */
    "warnings": string[];

    /** Creates a new ExpandResult instance. */
    constructor($$source: Partial<ExpandResult> = {}) {
        if (!("values" in $$source)) {
            this["values"] = [];
        }
        if (!("originalLen" in $$source)) {
            this["originalLen"] = 0;
        }
        if (!("expandedLen" in $$source)) {
            this["expandedLen"] = 0;
        }
        if (!("hasExpanded" in $$source)) {
            this["hasExpanded"] = false;
        }
        if (!("hasInferred" in $$source)) {
            this["hasInferred"] = false;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExpandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExpandResult {
        const $$createField0_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField0_0($$parsedSource["values"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new ExpandResult($$parsedSource as Partial<ExpandResult>);
    }
}

/**
 * VarInput 变量输入
 */
export class VarInput {
    /**
     * 变量名，如 "[A]", "[B]"
     */
    "name": string;

    /**
     * 值字符串（逗号/换行分隔）
     */
    "valueString": string;

    /** Creates a new VarInput instance. */
    constructor($$source: Partial<VarInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("valueString" in $$source)) {
            this["valueString"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VarInput instance from a string or object.
     */
    static createFrom($$source: any = {}): VarInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VarInput($$parsedSource as Partial<VarInput>);
    }
}

// Private type creation functions
const $$createType0 = VarInput.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
