// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ARPFact ARP表项
 */
export class ARPFact {
    /**
     * IP地址
     */
    "ipAddress": string;

    /**
     * MAC地址
     */
    "macAddress": string;

    /**
     * 接口
     */
    "interface": string;

    /**
     * 类型
     */
    "type": string;

    /**
     * 来源命令
     */
    "commandKey": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /** Creates a new ARPFact instance. */
    constructor($$source: Partial<ARPFact> = {}) {
        if (!("ipAddress" in $$source)) {
            this["ipAddress"] = "";
        }
        if (!("macAddress" in $$source)) {
            this["macAddress"] = "";
        }
        if (!("interface" in $$source)) {
            this["interface"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ARPFact instance from a string or object.
     */
    static createFrom($$source: any = {}): ARPFact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ARPFact($$parsedSource as Partial<ARPFact>);
    }
}

/**
 * AggregateFact 聚合组信息
 */
export class AggregateFact {
    /**
     * 聚合口名称
     */
    "aggregateName": string;

    /**
     * 成员端口列表
     */
    "memberPorts": string[];

    /**
     * 模式：lacp / static
     */
    "mode": string;

    /**
     * 来源命令
     */
    "commandKey": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /** Creates a new AggregateFact instance. */
    constructor($$source: Partial<AggregateFact> = {}) {
        if (!("aggregateName" in $$source)) {
            this["aggregateName"] = "";
        }
        if (!("memberPorts" in $$source)) {
            this["memberPorts"] = [];
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AggregateFact instance from a string or object.
     */
    static createFrom($$source: any = {}): AggregateFact {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("memberPorts" in $$parsedSource) {
            $$parsedSource["memberPorts"] = $$createField1_0($$parsedSource["memberPorts"]);
        }
        return new AggregateFact($$parsedSource as Partial<AggregateFact>);
    }
}

/**
 * DeviceIdentity 设备身份信息
 */
export class DeviceIdentity {
    /**
     * 厂商：huawei / h3c / cisco
     */
    "vendor": string;

    /**
     * 型号
     */
    "model": string;

    /**
     * 序列号
     */
    "serialNumber": string;

    /**
     * 版本
     */
    "version": string;

    /**
     * 主机名
     */
    "hostname": string;

    /**
     * 管理IP
     */
    "mgmtIp": string;

    /**
     * 机箱ID（LLDP）
     */
    "chassisId": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /** Creates a new DeviceIdentity instance. */
    constructor($$source: Partial<DeviceIdentity> = {}) {
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("mgmtIp" in $$source)) {
            this["mgmtIp"] = "";
        }
        if (!("chassisId" in $$source)) {
            this["chassisId"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceIdentity($$parsedSource as Partial<DeviceIdentity>);
    }
}

/**
 * FDBFact MAC地址表项
 */
export class FDBFact {
    /**
     * MAC地址
     */
    "macAddress": string;

    /**
     * VLAN ID
     */
    "vlan": number;

    /**
     * 接口
     */
    "interface": string;

    /**
     * 类型：dynamic / static
     */
    "type": string;

    /**
     * 来源命令
     */
    "commandKey": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /** Creates a new FDBFact instance. */
    constructor($$source: Partial<FDBFact> = {}) {
        if (!("macAddress" in $$source)) {
            this["macAddress"] = "";
        }
        if (!("vlan" in $$source)) {
            this["vlan"] = 0;
        }
        if (!("interface" in $$source)) {
            this["interface"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FDBFact instance from a string or object.
     */
    static createFrom($$source: any = {}): FDBFact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FDBFact($$parsedSource as Partial<FDBFact>);
    }
}

/**
 * InterfaceFact 接口信息
 */
export class InterfaceFact {
    /**
     * 接口名
     */
    "name": string;

    /**
     * 状态：up / down
     */
    "status": string;

    /**
     * 协议状态
     */
    "protocol": string;

    /**
     * 速率
     */
    "speed": string;

    /**
     * 双工模式
     */
    "duplex": string;

    /**
     * 描述
     */
    "description": string;

    /**
     * MAC地址
     */
    "macAddress": string;

    /**
     * IP地址
     */
    "ipAddress": string;

    /**
     * 是否聚合口
     */
    "isAggregate": boolean;

    /**
     * 所属聚合组ID
     */
    "aggregateId": string;

    /**
     * Cisco特有：VLAN或trunk
     */
    "vlan"?: string;

    /**
     * Cisco特有：是否为trunk
     */
    "isTrunk"?: boolean;

    /** Creates a new InterfaceFact instance. */
    constructor($$source: Partial<InterfaceFact> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("speed" in $$source)) {
            this["speed"] = "";
        }
        if (!("duplex" in $$source)) {
            this["duplex"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("macAddress" in $$source)) {
            this["macAddress"] = "";
        }
        if (!("ipAddress" in $$source)) {
            this["ipAddress"] = "";
        }
        if (!("isAggregate" in $$source)) {
            this["isAggregate"] = false;
        }
        if (!("aggregateId" in $$source)) {
            this["aggregateId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceFact instance from a string or object.
     */
    static createFrom($$source: any = {}): InterfaceFact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterfaceFact($$parsedSource as Partial<InterfaceFact>);
    }
}

/**
 * LLDPFact LLDP邻居信息
 */
export class LLDPFact {
    /**
     * 本地接口
     */
    "localInterface": string;

    /**
     * 邻居设备名
     */
    "neighborName": string;

    /**
     * 邻居机箱ID
     */
    "neighborChassis": string;

    /**
     * 邻居端口
     */
    "neighborPort": string;

    /**
     * 邻居管理IP
     */
    "neighborIp": string;

    /**
     * 邻居描述
     */
    "neighborDesc": string;

    /**
     * 来源命令
     */
    "commandKey": string;

    /**
     * 原始输出引用ID
     */
    "rawRefId": string;

    /** Creates a new LLDPFact instance. */
    constructor($$source: Partial<LLDPFact> = {}) {
        if (!("localInterface" in $$source)) {
            this["localInterface"] = "";
        }
        if (!("neighborName" in $$source)) {
            this["neighborName"] = "";
        }
        if (!("neighborChassis" in $$source)) {
            this["neighborChassis"] = "";
        }
        if (!("neighborPort" in $$source)) {
            this["neighborPort"] = "";
        }
        if (!("neighborIp" in $$source)) {
            this["neighborIp"] = "";
        }
        if (!("neighborDesc" in $$source)) {
            this["neighborDesc"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("rawRefId" in $$source)) {
            this["rawRefId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLDPFact instance from a string or object.
     */
    static createFrom($$source: any = {}): LLDPFact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLDPFact($$parsedSource as Partial<LLDPFact>);
    }
}

/**
 * ParseErrorDetail 解析错误详情
 */
export class ParseErrorDetail {
    "deviceIp": string;
    "commandKey": string;
    "error": string;
    "parseTime": string;

    /** Creates a new ParseErrorDetail instance. */
    constructor($$source: Partial<ParseErrorDetail> = {}) {
        if (!("deviceIp" in $$source)) {
            this["deviceIp"] = "";
        }
        if (!("commandKey" in $$source)) {
            this["commandKey"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("parseTime" in $$source)) {
            this["parseTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseErrorDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ParseErrorDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParseErrorDetail($$parsedSource as Partial<ParseErrorDetail>);
    }
}

/**
 * ParsedResult 解析结果
 */
export class ParsedResult {
    "taskId": string;
    "deviceIp": string;
    "parsedAt": time$0.Time;
    "identity"?: DeviceIdentity | null;
    "interfaces"?: InterfaceFact[];
    "lldpNeighbors"?: LLDPFact[];
    "fdbEntries"?: FDBFact[];
    "arpEntries"?: ARPFact[];
    "aggregates"?: AggregateFact[];
    "parseErrors"?: string[];

    /** Creates a new ParsedResult instance. */
    constructor($$source: Partial<ParsedResult> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("deviceIp" in $$source)) {
            this["deviceIp"] = "";
        }
        if (!("parsedAt" in $$source)) {
            this["parsedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParsedResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ParsedResult {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType12;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField3_0($$parsedSource["identity"]);
        }
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField4_0($$parsedSource["interfaces"]);
        }
        if ("lldpNeighbors" in $$parsedSource) {
            $$parsedSource["lldpNeighbors"] = $$createField5_0($$parsedSource["lldpNeighbors"]);
        }
        if ("fdbEntries" in $$parsedSource) {
            $$parsedSource["fdbEntries"] = $$createField6_0($$parsedSource["fdbEntries"]);
        }
        if ("arpEntries" in $$parsedSource) {
            $$parsedSource["arpEntries"] = $$createField7_0($$parsedSource["arpEntries"]);
        }
        if ("aggregates" in $$parsedSource) {
            $$parsedSource["aggregates"] = $$createField8_0($$parsedSource["aggregates"]);
        }
        if ("parseErrors" in $$parsedSource) {
            $$parsedSource["parseErrors"] = $$createField9_0($$parsedSource["parseErrors"]);
        }
        return new ParsedResult($$parsedSource as Partial<ParsedResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DeviceIdentity.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = InterfaceFact.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = LLDPFact.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = FDBFact.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ARPFact.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = AggregateFact.createFrom;
const $$createType12 = $Create.Array($$createType11);
